/* Real Chromium/IndexedDB/WebCrypto, synthetic fixtures only. No physical Android claim. */
'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),results=[],requests=[];
const server=http.createServer((req,res)=>{requests.push({method:req.method,url:req.url});const url=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(url.pathname.endsWith('/')?url.pathname+'index.html':url.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.js':'application/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const ctx=await browser.newContext({viewport:{width:1280,height:960},acceptDownloads:true});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);fs.mkdirSync('test-artifacts',{recursive:true});
 const pass=x=>{results.push(x);console.log('PASS '+x);};const saved=()=>page.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy&&document.querySelector('#status').textContent.startsWith('Saved'));const nav=r=>page.evaluate(r=>navigate(r),r);
 let recovered;
 try{
  await page.goto(base+'/#archive');await saved();await page.getByRole('heading',{name:'Private archive',exact:true}).waitFor();assert.equal(await page.locator('#main table').count(),0);assert.equal(await page.evaluate(()=>ArchiveCore.coverage(S).accountCompleteness),null);pass('empty archive boots with unknown account coverage and no preloaded private records');
  await page.locator('[data-action="archive-enable"]').click();await saved();assert.equal(await page.evaluate(()=>S.archive.captureEnabled),true);
  await page.evaluate(async()=>{await mutate('FIXTURE_PROJECTS','Synthetic projects only',s=>{for(const [id,title] of [['alpha','Archive experiment'],['beta','Lexicon experiment']])s.threads.push({id,title,objective:'Synthetic test',last:'',next:'Verify',state:'CONTINUE',open:[],waiting:'',attention:false});});});
  const original='Term: Lumenfold — an imagined fold of light.\r\nDecision: Preserve the original.\nNext action: test retrieval?\nPRIVATE_GOBLIN_MARKER embarrassing imaginary socks\nfixture-person@example.invalid';
  await nav('capture');await page.waitForFunction(()=>document.querySelector('#captureForm')?.getAttribute('aria-busy')==='false');
  await page.locator('#text').evaluate((el,raw)=>{const d=new DataTransfer();d.setData('text/plain',raw);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));},original);
  await page.locator('#captureConsent').check();await page.locator('#captureForm button.primary').click();await saved();await page.waitForFunction(()=>S.archive?.items?.length>=3);
  assert.equal(await page.evaluate(()=>S.sources[0].text),original);assert.equal(await page.evaluate(()=>S.notes.length),0);assert.ok(await page.evaluate(()=>S.archive.items.every(x=>x.privacy==='private'&&x.review==='candidate')));pass('opt-in capture atomically preserves exact CRLF/LF source and private candidate index');
  await page.reload();await saved();await nav('archive');await page.locator('#archiveQuery').fill('Lumenfold');assert.equal(await page.locator('.archive-item').count(),1);pass('search retrieves persisted source-linked record after reload');
  await page.locator('[data-action="archive-review"]').click();await page.waitForFunction(()=>document.querySelector('#archiveReview')?.getAttribute('aria-busy')==='false');assert.equal(await page.locator('#arConfirm').isChecked(),false);
  await page.locator('#arSummary').fill('Lumenfold is a synthetic test term; this is a reviewed interpretation.');await page.locator('#arDomain').fill('Language');await page.locator('[name="arProject-alpha"]').check();await page.locator('[name="arProject-beta"]').check();await page.locator('#arReason').fill('Checked the source line.');await page.locator('#arConfirm').check();await page.locator('#archiveReview button.primary').click();await saved();await page.waitForFunction(()=>ArchiveCore.current(S).some(x=>x.kind==='term'&&x.review==='confirmed'));
  const termId=await page.evaluate(()=>ArchiveCore.current(S).find(x=>x.kind==='term'&&x.review==='confirmed').id);assert.equal(await page.evaluate(()=>S.archive.items.filter(x=>x.kind==='term').length),2);assert.equal(await page.evaluate(id=>S.archive.items.find(x=>x.id===id).projectIds.length,termId),2);pass('review adds immutable version, exact evidence and multiple project links');
  await page.locator(`[data-archive-select="${termId}"]`).check();await page.locator('[data-action="archive-capsule"]').click();const capsule=await page.locator('#archiveCapsule').inputValue();assert.ok(capsule.includes('Lumenfold'));assert.ok(!capsule.includes('PRIVATE_GOBLIN_MARKER'));assert.ok(!capsule.includes('fixture-person@'));const capDL=page.waitForEvent('download');await page.locator('#downloadArchiveCapsule').click();await (await capDL).saveAs('test-artifacts/context-capsule-SYNTHETIC.md');await page.locator('[data-action="close"]').click();pass('capsule downloads selected excerpts only, not unrelated private lines');
  await page.locator(`[data-action="archive-propose"][data-id="${termId}"]`).click();await page.waitForFunction(()=>document.querySelector('#archiveProposal')?.getAttribute('aria-busy')==='false');assert.equal(await page.locator('#apSummary').inputValue(),'');
  for(const [selector,text] of Object.entries({apTitle:'A retained-source experiment',apSummary:'An experiment kept original text separate from a reviewed interpretation.',apProject:'Continuity',apKind:'Engineering',apDate:'2026-10-03',apSupports:'A source-linked recovery test.',apLimits:'Not an independent security audit.'}))await page.locator('#'+selector).fill(text);
  await page.locator('#archiveProposal button.primary').click();await saved();await page.getByRole('heading',{name:'Publication review',exact:true}).waitFor();assert.equal(await page.evaluate(()=>ArchiveCore.publicExport(S).posts.length),0);pass('separate blank public composer creates an unapproved draft with no automatic release');
  await page.locator('[data-action="archive-approve-preview"]').click();assert.equal(await page.locator('#approvePublicConsent').isChecked(),false);await page.locator('#approvePublic').click();assert.match(await page.locator('#status').innerText(),/NOT SAVED/);assert.equal(await page.evaluate(()=>ArchiveCore.publicExport(S).posts.length),0);await page.locator('#approvePublicConsent').check();await page.locator('#approvePublic').click();await saved();await page.waitForFunction(()=>ArchiveCore.publicExport(S).posts.length===1);pass('fresh explicit approval is required after exact public preview');
  const publicDL=page.waitForEvent('download');await page.locator('[data-action="archive-export-public"]').click();const pub=await publicDL;await pub.saveAs('test-artifacts/public-SYNTHETIC.html');const html=fs.readFileSync('test-artifacts/public-SYNTHETIC.html','utf8');assert.ok(!html.includes('PRIVATE_GOBLIN_MARKER'));assert.ok(!html.includes('fixture-person@'));assert.ok(!html.includes('Lumenfold'));assert.ok(!html.includes(termId));assert.ok(!html.includes('<script'));pass('public HTML contains allowlisted derivative only, with no raw text or private IDs');
  const publicPage=await ctx.newPage();await publicPage.setContent(html);await publicPage.pdf({path:'test-artifacts/public-SYNTHETIC.pdf',format:'A4',printBackground:true});await publicPage.screenshot({path:'test-artifacts/public-SYNTHETIC.png',fullPage:true});await publicPage.close();pass('approved HTML has a real Chromium print-to-PDF output');
  const backup=await page.evaluate(()=>JSON.stringify({format:'ContinuityBackup/2',state:S}));
  recovered=await browser.newContext({viewport:{width:390,height:844}});const rp=await recovered.newPage();await rp.goto(base+'/#archive');await rp.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy);await rp.evaluate(async raw=>{await mutate('RESTORE_FIXTURE','Explicit synthetic separate-profile restore',s=>Object.assign(s,WorkspaceCore.backup(raw)),true);},backup);await rp.reload();await rp.waitForFunction(()=>typeof S!=='undefined'&&S?.archive?.items?.length);
  assert.equal(await rp.evaluate(()=>S.sources[0].text),original);assert.equal(await rp.evaluate(()=>ArchiveCore.publicExport(S).posts.length),0);assert.equal(await rp.evaluate(()=>S.archive.captureEnabled),false);assert.equal(await rp.evaluate(()=>S.archive.items.filter(x=>x.kind==='term').length),2);pass('independent-profile native IndexedDB recovery preserves source/genealogy and resets public approval + capture opt-in');
  const encryption=await page.evaluate(async()=>{const raw=JSON.stringify({format:'ContinuityBackup/2',state:S});const sealed=await SealedBackup.seal(raw,'Synthetic-only-test-passphrase');let rejected=false;try{await SealedBackup.open(sealed,'wrong-synthetic-passphrase');}catch{rejected=true;}return {rejected,equal:await SealedBackup.open(sealed,'Synthetic-only-test-passphrase')===raw};});assert.deepEqual(encryption,{rejected:true,equal:true});pass('existing WebCrypto sealed export preserves exact backup and rejects wrong passphrase');
  const newPage=await ctx.newPage();await newPage.goto(base+'/#archive');await newPage.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy);await page.evaluate(async()=>{await mutate('FIXTURE_CHANGE','Synthetic first-tab change',s=>s.threads[0].next='Changed in first tab');});const stale=await newPage.evaluate(async()=>{const okay=await mutate('STALE_FIXTURE','Must reject stale write',s=>s.threads[0].next='Stale tab');return {okay,status:document.querySelector('#status').textContent};});assert.equal(stale.okay,false);assert.match(stale.status,/NOT SAVED/);await newPage.close();pass('existing optimistic transaction rejects stale archive workspace writes');
  await nav('archive');await page.locator('#archiveQuery').fill('Lumenfold');await page.locator('[data-action="archive-review"]').click();await page.waitForFunction(()=>document.querySelector('#archiveReview')?.getAttribute('aria-busy')==='false');await page.locator('#arSummary').fill('Unfinished private revision');await page.locator('#arConfirm').check();await page.waitForFunction(()=>document.querySelector('.draft-status')?.textContent.includes('Draft saved'));await page.reload();await saved();await nav('archive');await page.locator('#archiveQuery').fill('Lumenfold');await page.locator('[data-action="archive-review"]').click();await page.waitForFunction(()=>document.querySelector('#archiveReview')?.getAttribute('aria-busy')==='false');assert.equal(await page.locator('#arSummary').inputValue(),'Unfinished private revision');assert.equal(await page.locator('#arConfirm').isChecked(),false);await page.locator('[data-action="close"]').click();pass('draft survives reload but review consent does not');
  await nav('archive');await page.locator('[data-action="archive-daily"]').click();const day=await page.evaluate(()=>new Date().toISOString().slice(0,10));await page.locator('#genesisDay').fill(day);await page.locator('#genesisBuild').click();assert.match(await page.locator('#genesisOutput').innerText(),/PRIVATE|capture coverage/i);await page.locator('[data-action="close"]').click();pass('Daily Genesis is private and distinguishes captured records from daily creative output');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await ctx.setOffline(true);await page.reload();await saved();await nav('archive');assert.ok(await page.getByRole('heading',{name:'Private archive',exact:true}).isVisible());await ctx.setOffline(false);pass('version-pinned shell loads the archive UI offline after service-worker installation');
  await page.setViewportSize({width:390,height:844});await page.locator('#archiveQuery').fill('');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-artifacts/archive-mobile-SYNTHETIC.png',fullPage:true});pass('390px viewport fits without horizontal overflow; no native Android claim');
  await page.goto(base+'/proof-of-progress/');await page.getByRole('heading',{name:'Proof of Progress',exact:true}).waitFor();assert.equal(await page.locator('#status').count(),0);assert.ok(!(await page.content()).includes('PRIVATE_GOBLIN_MARKER'));pass('service worker does not substitute the private app shell for the public subpage');
  assert.ok(requests.every(r=>r.method==='GET'));assert.ok(requests.every(r=>!r.url.includes('PRIVATE_GOBLIN_MARKER')&&!r.url.includes('Lumenfold')));assert.deepEqual(errors,[]);pass('source text never appears in requests and no uncaught application errors');
  fs.writeFileSync('test-artifacts/archive-browser-results.json',JSON.stringify({passed:results.length,scenarios:results,browser:await browser.version(),physicalAndroid:false},null,2));
 }catch(e){fs.writeFileSync('test-artifacts/archive-browser-failure.txt',String(e.stack)+'\n'+errors.join('\n'));console.error(await page.evaluate(()=>({url:location.href,route:typeof route!=='undefined'?route:null,status:document.querySelector('#status')?.textContent,dialog:document.querySelector('dialog')?.innerText})).catch(()=>({})));await page.screenshot({path:'test-artifacts/archive-browser-failure.png',fullPage:true}).catch(()=>{});throw e;}
 finally{await recovered?.close();await ctx.close();await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
