/* Real browser + native IndexedDB tests. Run on a normal host or GitHub Actions. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const W=require('../site/workspace-core.js');
const root=path.resolve(__dirname,'../site'),results=[];
const pass=name=>{results.push(name);console.log('PASS '+name);};
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;const p=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!p.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}try{const bytes=fs.readFileSync(p);res.writeHead(200,{'Content-Type':({'.js':'application/javascript','.css':'text/css','.html':'text/html'})[path.extname(p)]||'text/plain'});res.end(bytes);}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const ctx=await browser.newContext({viewport:{width:1280,height:900},permissions:['clipboard-read','clipboard-write']});const page=await ctx.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 fs.mkdirSync('test-artifacts',{recursive:true});
 try{
  await page.goto(base);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));
  assert.ok(await page.getByText('Start with one unfinished thing.').isVisible());pass('native IndexedDB boot with empty workspace');
  await page.locator('main [data-action="new-thread"]').first().click();await page.locator('#title').fill('Real test project');await page.locator('#objective').fill('Write an article without losing decisions.');await page.locator('#next').fill('Draft the introduction.');await page.locator('#threadForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});await page.getByRole('heading',{name:'Real test project',exact:true}).waitFor();pass('create an intention and commit before showing saved');
  await page.locator('main [data-action="add-source"]').first().click();await page.locator('#sourceTitle').fill('Source conversation');await page.locator('#sourceThread').selectOption({label:'Real test project'});await page.locator('#sourceText').fill('User: We decided to preserve the original.\nAssistant: Replace everything.\nSecret unselected line.\n<img src=x onerror="window.pwned=true">');await page.locator('#sourceForm button.primary').click();await page.getByRole('heading',{name:'Source conversation',exact:true}).waitFor();assert.equal(await page.locator('.source-line').count(),4);assert.equal(await page.locator('.source img').count(),0);pass('paste and preserve source; markup rendered inert');
  await page.locator('[data-action="checkpoint"][data-line="1"]').click();await page.locator('#noteKind').selectOption('decision');await page.locator('#statement').fill('Keep the original.');await page.locator('#reviewed').check();await page.locator('#noteForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});assert.ok(await page.getByText('Keep the original.',{exact:true}).isVisible());pass('review a decision with exact source evidence');
  await page.locator('[data-nav="intentions"]').click();await page.locator('[data-action="pack"]').first().click();const pack=await page.locator('#packText').inputValue();assert.ok(pack.includes('Keep the original.'));assert.ok(pack.includes(':L1-L1]'));assert.ok(!pack.includes('Secret unselected line'));assert.ok(!pack.includes('Replace everything'));await page.locator('[data-action="copy-pack"]').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),pack);pass('copy source-linked Resume Pack without unselected conversation');
  const dl=page.waitForEvent('download');await page.locator('[data-action="download-pack"]').click();const download=await dl;assert.ok(download.suggestedFilename().endsWith('.md'));pass('download Markdown handoff');
  await page.reload();await page.locator('#packText').waitFor();assert.ok((await page.locator('#packText').inputValue()).includes('Keep the original.'));pass('native persistence survives reload');
  await page.locator('[data-action="add-source"]').click();await page.locator('#sourceTitle').fill('Unfinished source draft');await page.locator('#sourceText').fill('Saved draft text.');await page.waitForFunction(()=>document.querySelector('dialog .draft-status').textContent.includes('Draft saved'));
  await page.reload();await page.locator('#packText').waitFor();await page.locator('[data-action="add-source"]').click();await page.waitForFunction(()=>document.querySelector('#sourceTitle').value==='Unfinished source draft');assert.equal(await page.locator('#sourceText').inputValue(),'Saved draft text.');await page.locator('[data-action="close"]').click();pass('source form draft survives reload');
  const second=await ctx.newPage();await second.goto(base);await second.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));await second.locator('main [data-action="new-thread"]').first().click();await second.locator('#title').fill('Stale attempted write');
  await page.locator('[data-nav="capture"]').click();await page.locator('#text').fill('New work from first tab.');await page.locator('#captureConsent').check();await page.locator('#captureForm button.primary').click();await page.getByText('New work from first tab.',{exact:true}).waitFor();await second.locator('#threadForm button.primary').click();await second.waitForFunction(()=>document.querySelector('#status').textContent.includes('NOT SAVED'));assert.ok((await second.locator('#status').textContent()).includes('Another tab'));await second.close();pass('stale tab write rejected by native transaction revision check');
  await page.locator('[data-nav="sources"]').click();await page.locator('[data-action="source"]').first().click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'test-artifacts/source-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});pass('390px mobile source screen has no horizontal overflow');
  await page.locator('[data-nav="backup"]').click();const saved=await page.evaluate(()=>JSON.stringify({format:'ContinuityBackup/2',state:S}));const input=page.locator('#backupFile');await input.setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":"99"}')});await page.waitForFunction(()=>document.querySelector('#importPreview').textContent.includes('Rejected'));assert.ok(await page.locator('#restore').isDisabled());pass('malformed restore rejected before data mutation');
  await input.setInputFiles({name:'empty.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'ContinuityBackup/2',state:W.empty()}))});await page.locator('#restore:enabled').waitFor();page.once('dialog',d=>d.accept());await page.locator('#restore').click();await page.getByText('Start with one unfinished thing.').waitFor();const recovery=await page.evaluate(()=>store.read('recovery','before-import'));assert.equal(recovery.state.sources.length,2);assert.equal(recovery.state.notes.length,1);pass('restore retains entire prior workspace in recovery');
  await page.locator('[data-nav="backup"]').click();await page.locator('#backupFile').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(saved)});await page.locator('#restore:enabled').waitFor();page.once('dialog',d=>d.accept());await page.locator('#restore').click();await page.getByRole('heading',{name:'Real test project',exact:true}).waitFor();pass('full backup round trip through native storage and UI');
  await page.locator('[data-nav="intentions"]').click();await page.locator('[data-action="pack"]').click();await page.screenshot({path:'test-artifacts/resume-pack-desktop.png',fullPage:true});
  const legacyCtx=await browser.newContext();const legacy=W.empty();legacy.version='0.10.0';legacy.threads=[{id:'old',title:'Legacy work',objective:'Preserve me',last:'Yesterday',next:'Resume',state:'CONTINUE',open:[],waiting:'',attention:true}];delete legacy.sources;delete legacy.notes;const old=JSON.stringify(legacy);await legacyCtx.addInitScript(raw=>localStorage.setItem('continuity-live-lab/0.9',raw),old);const lp=await legacyCtx.newPage();await lp.goto(base);await lp.getByRole('heading',{name:'Legacy work',exact:true}).waitFor();assert.equal(await lp.evaluate(()=>store.read('recovery','legacy')),old);assert.equal(await lp.evaluate(()=>localStorage.getItem('continuity-live-lab/0.9')),old);pass('v0.10 migrates to IndexedDB without deleting legacy bytes');await legacyCtx.close();
  assert.deepEqual(errors,[]);pass('no uncaught JavaScript errors');
  fs.writeFileSync('test-artifacts/results.json',JSON.stringify({passed:results.length,scenarios:results},null,2));
 }catch(e){console.error('BROWSER_DIAGNOSTICS',await page.evaluate(async()=>({status:document.querySelector('#status')?.textContent,draftStatus:document.querySelector('dialog .draft-status')?.textContent,draftDirty,draftJob,tab,savedSourceDraft:await store.read('drafts',draftKey('source'))})).catch(err=>String(err)));await page.screenshot({path:'test-artifacts/failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('test-artifacts/failure.txt',String(e.stack)+'\n'+errors.join('\n'));throw e;}
 finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
