const {test}=require('node:test'),a=require('node:assert/strict');
const W=require('../site/workspace-core.js'),O=require('../site/operations-core.js'),F=require('../site/capture-family-core.js');
const AT='2026-10-03T23:15:00.000Z';
function plan(fields={},token='draft-one',at=AT){return F.prepare({text:'A recoverable thought.\nOne original.',...fields},token,at);}
function saved(fields={}){return F.apply(W.empty(),plan(fields),true).state;}
test('capture saves one exact source plus a linked unreviewed capture',()=>{const raw='  A thought.\r\n\r\n\tIt stays.  \n',p=plan({text:raw}),r=F.apply(W.empty(),p,true);a.equal(r.state.sources.length,1);a.equal(r.state.captures.length,1);a.equal(r.state.sources[0].text,raw);a.equal(r.state.captures[0].text,raw);a.equal(r.state.captures[0].sourceId,r.state.sources[0].id);a.equal(r.state.sources[0].speaker,'unknown');a.equal(r.state.captures[0].reviewState,'unreviewed');a.equal(r.state.captures[0].status,'UNPROCESSED');a.equal(r.state.notes.length,0);a.equal(r.state.threads.length,0);});
test('planning and apply leave caller state and plan unchanged',()=>{const s=W.empty(),p=plan(),before=JSON.stringify({s,p});F.apply(s,p,true);a.equal(JSON.stringify({s,p}),before);});
test('saving requires fresh explicit consent, including retries',()=>{const p=plan();for(const consent of [undefined,null,false,'true',1])a.throws(()=>F.apply(W.empty(),p,consent),/Confirm local/);const s=F.apply(W.empty(),p,true).state;a.throws(()=>F.apply(s,p,false),/Consent is never restored/);});
test('source version, method and supplied timestamp remain distinct from received time',()=>{const s=saved({method:'intent-observation',observedAt:'2026-10-03T14:12:00-04:00',speaker:'mixed',inputBasis:'clipboard-text/plain'}),p=s.sources[0].captureOrigin;a.equal(p.sourceVersion,1);a.equal(p.appVersion,'0.18.0');a.equal(p.method,'intent-observation');a.equal(p.observedAt,'2026-10-03T14:12:00-04:00');a.equal(p.receivedAt,AT);a.equal(s.sources[0].speaker,'mixed');a.equal(p.consentRecord.scope,'local-original-and-capture');});
test('text transcript means supplied text and has no automatic attribution',()=>{const s=saved({method:'manual-transcript'});a.equal(s.sources[0].captureOrigin.method,'manual-transcript');a.equal(s.sources[0].speaker,'unknown');a.equal(s.sources[0].captureOrigin.observedAt,null);});
test('retry after committed save and failed draft cleanup cannot duplicate records',()=>{const first=F.apply(W.empty(),plan(),true),r=F.apply(first.state,plan({},'draft-one','2026-10-04T01:00:00.000Z'),true);a.equal(r.alreadySaved,true);a.equal(r.sourceId,first.sourceId);a.equal(r.captureId,first.captureId);a.deepEqual(r.state,first.state);a.equal(r.state.sources[0].createdAt,AT);});
test('retry also respects later archive status and source-to-project linkage',()=>{const s=saved();s.captures[0].status='ARCHIVED';s.threads.push({id:'t',title:'Thread',objective:'',last:'',next:'',open:[],waiting:'',state:'CONTINUE'});s.sources[0].threadId='t';const r=F.apply(s,plan(),true);a.equal(r.alreadySaved,true);a.equal(r.state.captures[0].status,'ARCHIVED');a.equal(r.state.sources[0].threadId,'t');});
test('reusing a token for changed original or metadata is rejected',()=>{const s=saved();for(const fields of [{text:'Different'},{context:'Different'},{speaker:'user'},{method:'manual-transcript'},{observedAt:'2026-10-03T10:00:00Z'}])a.throws(()=>F.apply(s,plan(fields),true),/already saved different/);});
test('separate intentional capture can repeat text with its own evidence record',()=>{const s=saved(),r=F.apply(s,plan({},'draft-two'),true);a.equal(r.state.captures.length,2);a.equal(r.state.sources.length,2);a.notEqual(r.state.sources[0].id,r.state.sources[1].id);});
test('tampered preview and colliding source ID fail without replacing evidence',()=>{const p=plan(),s=W.empty();p.source.text='tampered';a.throws(()=>F.apply(s,p,true),/preview changed/);const good=plan();s.sources.push({...good.source,text:'Existing original'});a.throws(()=>F.apply(s,good,true),/collision/);a.equal(s.sources[0].text,'Existing original');});
test('validation rejects broken links, mismatched originals, duplicate tokens and invalid provenance',()=>{for(const edit of [s=>s.captures[0].sourceId='missing',s=>s.captures[0].text='different',s=>s.sources[0].captureOrigin.sourceVersion=2,s=>s.captures.push({...s.captures[0],id:'other'}),s=>s.sources[0].captureOrigin.reviewState='confirmed']){const s=saved();edit(s);a.throws(()=>F.validate(s));}});
test('legacy captures with no invented source evidence remain supported',()=>{const s=W.empty();s.captures.push({id:'old',type:'note',text:'Legacy',context:'',at:AT,status:'UNPROCESSED'});const checked=F.validate(s);a.equal(checked.sources.length,0);a.equal(checked.captures[0].sourceId,undefined);});
test('search retrieves exact originals without confirming decisions',()=>{const s=saved({text:'Keep the improbable copper moon.\nNever overwrite it.'});const results=W.search(s,'copper moon');a.ok(results.some(x=>x.kind==='source'&&x.id===s.sources[0].id));a.ok(results.some(x=>x.kind==='capture'&&x.id===s.captures[0].id));a.equal(s.notes.length,0);});
test('full existing backup round trip retains capture metadata, raw source, and source link',()=>{const s=saved({text:'\ttrace\r\nline two\rline three\n ',method:'intent-observation',observedAt:'2026-10-03T11:30:00-04:00'}),out=W.backup(JSON.stringify({format:'ContinuityBackup/2',state:s}));a.deepEqual(out,s);a.equal(out.captures[0].sourceId,out.sources[0].id);const invalid=JSON.parse(JSON.stringify(s));invalid.captures[0].sourceId='lost';a.throws(()=>W.backup(JSON.stringify({format:'ContinuityBackup/2',state:invalid})),/source link/);});
test('project exports retain source metadata but intentionally omit capture inbox records',()=>{const s=saved();s.threads.push({id:'t',title:'Thread',objective:'',last:'',next:'',open:[],waiting:'',state:'CONTINUE'});s.sources[0].threadId='t';const p=O.createProject(s,'t','packet',AT);a.equal(p.state.captures.length,0);a.deepEqual(p.state.sources[0].captureOrigin,s.sources[0].captureOrigin);a.equal(F.validate(p.state).sources.length,1);});
test('reconstructed device-trace boundary remains a single newline, not invented blank line',()=>{
 // Regression input reconstructed from screenshot/OCR evidence. It is NOT a
 // device clipboard dump and does not establish which upstream app changed it.
 const raw='at population scale.\nThe important distinction';const s=saved({text:raw,method:'intent-observation'});a.equal(s.sources[0].text,raw);a.equal(s.sources[0].text.includes('\n\n'),false);a.equal(W.search(s,'population distinction').length,2);
});
test('plain-text paste splice preserves CRLF, CR, whitespace and pasted newlines',()=>{const raw='one\r\ntwo\rthree\n';a.equal(F.editorText(raw),'one\ntwo\nthree\n');a.equal(F.spliceText(raw,4,7,'  second\r\nline  '),'one\r\n  second\r\nline  \rthree\n');a.equal(F.spliceText('',0,0,' \r\ntrace\n '),' \r\ntrace\n ');});
test('ordinary editor edits preserve unchanged original line terminators',()=>{a.equal(F.reconcileText('one\r\ntwo\rthree','one\nTWO\nthree'),'one\r\nTWO\rthree');a.equal(F.reconcileText('one\r\ntwo','one\ntwo'),'one\r\ntwo');a.equal(F.reconcileText('one\r\ntwo','onetwo'),'onetwo');a.equal(F.reconcileText('','hello\nthere'),'hello\nthere');});
test('pointer guard accepts a stable same target and rejects movement, target change, or canceled pointer',()=>{const r={left:10,top:20,width:100,height:40},down={target:'save',pointerId:2,rect:r};a.equal(F.stableAction(down,{...down,rect:{...r}}),true);a.equal(F.stableAction(down,{...down,rect:{...r,top:22}}),false);a.equal(F.stableAction(down,{...down,target:'delete'}),false);a.equal(F.stableAction(down,{...down,pointerId:3}),false);a.equal(F.stableAction(down,null),false);});
test('blank, binary, oversized, invalid attribution and ambiguous observation time are rejected',()=>{for(const fields of [{text:'  '},{text:'x\0y'},{text:'x'.repeat(20001)},{speaker:'certainly-me'},{method:'native-android'},{observedAt:'2026-10-03 12:00'},{observedAt:'2026-02-30T12:00:00Z'},{observedAt:'2026-10-03T24:00:00Z'}])a.throws(()=>plan(fields));a.throws(()=>plan({},'../../escape'));});
