/* Two isolated browser contexts = separate real IndexedDB workspaces. No simulated storage. */
const {chromium}=require('playwright'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),prefix='/artificial-continuity/',results=[],requests=[];
const server=http.createServer((req,res)=>{requests.push(req.url);const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const f=path.resolve(root,u.pathname.slice(prefix.length)||'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+prefix;
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const ca=await browser.newContext({viewport:{width:1440,height:1000}}),cb=await browser.newContext({viewport:{width:390,height:844}}),pa=await ca.newPage(),pb=await cb.newPage(),errors=[];
 for(const p of [pa,pb]){p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());}
 const pass=t=>{results.push(t);console.log('PASS '+t);},ready=p=>p.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy&&document.querySelector('#status')?.textContent.startsWith('Saved'));
 const nav=(p,r,id=null)=>p.evaluate(([r,id])=>navigate(r,id),[r,id]);
 async function file(p,raw){await nav(p,'exchange');await p.locator('#exchangeFile').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(raw)});}
 async function send(p,thread,encrypted=false){await nav(p,'exchange',thread);await p.locator('#prepareExchange').click();await p.locator('#sealExchange').waitFor();if(encrypted){await p.locator('#exchangePass').fill('A long private testing phrase');await p.locator('#exchangePassConfirm').fill('A long private testing phrase');}
  const download=p.waitForEvent('download');await p.locator(encrypted?'#sealExchange':'#plainExchange').click();const d=await download;await ready(p);return fs.readFileSync(await d.path(),'utf8');}
 async function saveReview(p){await p.locator('#exchangeConsent').check();await p.locator('#applyExchange').click();await p.waitForURL('**/#project/*');await ready(p);}
 fs.mkdirSync('test-artifacts',{recursive:true});
 try{
  await pa.goto(base);await ready(pa);await pb.goto(base+'#exchange');await ready(pb);a.equal(await pb.locator('#prepareExchange').isDisabled(),true);pass('exchange deep link opens after startup with safe empty workspace');
  await pa.locator('[data-action="new-thread"]').first().click();await pa.waitForFunction(()=>document.querySelector('#threadForm')?.getAttribute('aria-busy')==='false');await pa.locator('#title').fill('Two-device test');await pa.locator('#objective').fill('Preserve actual work');await pa.locator('#next').fill('Original next step');await pa.locator('#threadForm .primary').click();await ready(pa);
  const aid=await pa.evaluate(()=>S.threads[0].id);
  await pa.evaluate(async aid=>{await mutate('TEST_FIXTURE','Fictional source evidence',s=>{const src=W.makeSource(s,{title:'Fixture original',text:'User: PRIVATE_EXCHANGE_SENTINEL\n<b>Not active HTML</b>',threadId:aid,speaker:'mixed'},uid(),now());s.sources.push(src);s.notes.push(W.checkpoint(s,{sourceId:src.id,threadId:aid,kind:'constraint',statement:'Keep original evidence',start:1,end:1,reviewed:true},uid(),now()));});},aid);await ready(pa);await nav(pa,'project',aid);await pa.locator('[data-action="project-exchange"]').click();await pa.locator('#prepareExchange').waitFor();pass('real project offers phone/desktop workflow without recreating its intention');
  await pa.locator('#prepareExchange').click();await pa.locator('#sealExchange').waitFor();await pa.locator('#exchangePass').fill('A long private testing phrase');await pa.locator('#exchangePassConfirm').fill('does not match');await pa.locator('#sealExchange').click();await pa.waitForFunction(()=>document.querySelector('#exchangeExportStatus').textContent.includes('do not match'));a.equal(await pa.evaluate(()=>S.threads[0].exchangeProjectId),undefined);pass('mismatched passphrases do not change exchange metadata');
  const encrypted=await send(pa,aid,true);a.ok(!encrypted.includes('PRIVATE_EXCHANGE_SENTINEL'));a.equal(await pa.locator('#exchangePass').inputValue(),'');a.ok(!JSON.stringify(await pa.evaluate(()=>S)).includes('private testing phrase'));pass('encrypted download protects file contents and does not persist the passphrase');
  await file(pb,encrypted);await pb.locator('#exchangeUnlock').waitFor();await pb.locator('#exchangeUnlock').fill('A wrong but long passphrase');await pb.locator('#unlockExchange').click();await pb.waitForFunction(()=>document.querySelector('#exchangeImportStatus').textContent.includes('Could not decrypt'));a.equal(await pb.evaluate(()=>S.threads.length),0);pass('wrong password leaves receiving workspace untouched');
  await pb.locator('#exchangeUnlock').fill('A long private testing phrase');await pb.locator('#unlockExchange').click();await pb.locator('#exchangeConsent').waitFor();a.equal(await pb.evaluate(()=>S.threads.length),0);a.ok((await pb.locator('#exchangeReview').innerText()).includes('Incoming intention fields'));pass('decrypting shows review fields but imports nothing');
  await pb.locator('#exchangeReview details').last().locator('summary').click();await pb.locator('[data-inspect-exchange]').first().click();a.ok((await pb.locator('#dialog pre').innerText()).includes('<b>Not active HTML</b>'));a.equal(await pb.locator('#dialog pre b').count(),0);await pb.locator('#dialog [data-action="close"]').click();pass('incoming originals can be inspected and markup stays inert');
  await pb.locator('#exchangeEvidence').check();await saveReview(pb);const bid=await pb.evaluate(()=>S.threads[0].id);a.equal(await pb.evaluate(()=>S.notes[0].reviewState),'pending');a.equal(await pb.evaluate(()=>S.sources.length),1);pass('first import creates one project and pending source-backed checkpoints');
  await pb.locator('[data-action="edit-thread"]').first().click();await pb.waitForFunction(()=>document.querySelector('#threadForm')?.getAttribute('aria-busy')==='false');await pb.locator('#next').fill('Phone next action');await pb.locator('#last').fill('Phone progress');await pb.locator('#threadForm .primary').click();await ready(pb);
  await pb.evaluate(async bid=>{await mutate('TEST_FIXTURE','Fictional additional evidence',s=>{const src=W.makeSource(s,{title:'Phone source',text:'New phone evidence',threadId:bid,speaker:'user'},uid(),now());s.sources.push(src);s.notes.push(W.checkpoint(s,{sourceId:src.id,threadId:bid,kind:'context',statement:'Phone context',start:1,end:1,reviewed:true},uid(),now()));});},bid);
  const incoming=await send(pb,bid);await pa.evaluate(async aid=>{await mutate('TEST_FIXTURE','Independent desktop progress',s=>s.threads.find(t=>t.id===aid).next='Desktop next action');},aid);await ready(pa);await file(pa,incoming);await pa.locator('#exchange-next').waitFor();a.ok((await pa.locator('#exchangeReview').innerText()).includes('CONFLICT'));a.equal(await pa.locator('#exchange-next').inputValue(),'');await pa.locator('#chooseIncomingOnly').click();a.equal(await pa.locator('#exchange-last').inputValue(),'incoming');a.equal(await pa.locator('#exchange-next').inputValue(),'');await pa.locator('#exchangeConsent').check();a.equal(await pa.locator('#applyExchange').isDisabled(),true);pass('two-device conflicts stay unresolved when applying incoming-only suggestions');
  await pa.locator('#exchange-next').selectOption('local');await pa.locator('#exchangeEvidence').check();await saveReview(pa);a.equal(await pa.evaluate(()=>S.threads.length),1);a.equal(await pa.evaluate(()=>S.threads[0].next),'Desktop next action');a.equal(await pa.evaluate(()=>S.threads[0].last),'Phone progress');a.equal(await pa.evaluate(()=>S.sources.length),2);a.equal(await pa.evaluate(()=>S.notes[0].reviewState),'confirmed');a.equal(await pa.evaluate(()=>S.notes[1].reviewState),'pending');pass('reviewed return updates existing project while preserving local decision and adding pending evidence');
  const recovery=await pa.evaluate(()=>store.read('recovery','before-import'));a.equal(recovery.state.sources.length,1);pass('transactional pre-update recovery snapshot preserves original workspace');
  await file(pa,incoming);await pa.waitForFunction(()=>document.querySelector('#exchangeImportStatus').textContent.includes('already applied'));a.equal(await pa.evaluate(()=>S.sources.length),2);pass('replayed file does not duplicate projects or evidence');
  const nextReturn=await send(pa,aid);await file(pb,nextReturn);await pb.locator('#exchange-next').waitFor();a.ok((await pb.locator('#exchangeReview').innerText()).includes('locally remembered baseline matches'));await pb.locator('#chooseIncomingOnly').click();await saveReview(pb);a.equal(await pb.evaluate(()=>S.threads[0].next),'Desktop next action');pass('second return round trip uses a remembered baseline across devices');
  const fresh=await send(pb,bid);await file(pa,fresh);await pa.locator('#exchangeConsent').check();await pa.evaluate(async()=>mutate('TEST_FIXTURE','Edited since review',s=>s.threads[0].last='More recent local progress'));await ready(pa);await pa.locator('#applyExchange').click();await pa.waitForFunction(()=>document.querySelector('#exchangeApplyStatus').textContent.includes('changed after'));a.equal(await pa.evaluate(()=>S.threads[0].last),'More recent local progress');pass('preview becomes stale after local edit and cannot overwrite it');
  const tampered=JSON.parse(fresh);tampered.state.threads[0].title='Modified bytes';await file(pa,JSON.stringify(tampered));await pa.waitForFunction(()=>document.querySelector('#exchangeImportStatus').textContent.includes('integrity'));pass('corrupted exchange rejected without mutation');
  await pa.evaluate(()=>navigator.serviceWorker.ready);await pa.waitForFunction(()=>!!navigator.serviceWorker.controller);await ca.setOffline(true);await nav(pa,'exchange');await pa.reload();await ready(pa);await pa.locator('#exchangeFile').waitFor();await file(pa,fresh);await pa.locator('#exchangeConsent').waitFor();pass('file review and exchange module reload work offline with native service worker cache');await ca.setOffline(false);
  await pa.screenshot({path:'test-artifacts/exchange-desktop.png',fullPage:true});await pa.setViewportSize({width:390,height:844});a.ok(await pa.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await pa.screenshot({path:'test-artifacts/exchange-phone.png',fullPage:true});pass('390px phone reconciliation view fits without horizontal overflow');
  a.deepEqual(errors,[]);a.ok(requests.every(u=>!u.includes('PRIVATE_')));pass('no browser errors or private source content in host request URLs');
 }catch(e){await pa.screenshot({path:'test-artifacts/exchange-failure-desktop.png',fullPage:true}).catch(()=>{});await pb.screenshot({path:'test-artifacts/exchange-failure-phone.png',fullPage:true}).catch(()=>{});throw e;}
 finally{fs.writeFileSync('test-artifacts/exchange-results.json',JSON.stringify({passed:results.length,scenarios:results,errors},null,2));await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
