const {test}=require('node:test'),a=require('node:assert/strict');
const W=require('../site/workspace-core.js'),O=require('../site/operations-core.js'),X=require('../site/exchange-core.js'),B=require('../site/sealed-backup.js');
const at='2026-09-26T20:00:00.000Z';let n=0;const id=()=>`generated-${++n}`;
function fixture(){const s=W.empty();s.threads.push({id:'project-1',title:'Fictional test project',objective:'Build something useful',last:'Decisions recorded',next:'Test it',open:['Is it recoverable?'],state:'CONTINUE',waiting:'',attention:false});s.sources.push(W.makeSource(s,{title:'Original source',text:'User: preserve the original\nAssistant: a suggestion',threadId:'project-1',speaker:'mixed'},'source-1',at));s.notes.push(W.checkpoint(s,{sourceId:'source-1',threadId:'project-1',kind:'constraint',statement:'Preserve original material',start:1,end:1,reviewed:true},'note-1',at));return W.validate(s);}
async function pair(){const a0=fixture(),p=await X.makePacket(a0,'project-1','initial',at),a1=await X.rememberExport(a0,'project-1',p),b1=await X.apply(W.validate(W.empty()),await X.plan(W.validate(W.empty()),p),{},{evidence:true},id,at);return {a1,b1:b1.state,bid:b1.threadId,p};}
function keep(plan){return Object.fromEntries(plan.rows.map(r=>[r.key,'local']));}
test('exchange snapshot keeps full originals and excludes unrelated work',async()=>{const s=fixture();s.threads.push({...s.threads[0],id:'other',title:'PRIVATE_UNRELATED'});s.sources.push(W.makeSource(s,{title:'Private',text:'PRIVATE_SENTINEL',threadId:'other',speaker:'user'},'source-2',at));const p=await X.makePacket(s,'project-1','p',at);a.ok(!JSON.stringify(p).includes('PRIVATE_'));a.equal(p.state.sources[0].text,s.sources[0].text);});
test('canonical packet round trip and stable content identifiers',async()=>{const p=await X.makePacket(fixture(),'project-1','p',at);a.deepEqual(await X.parse(JSON.stringify(p)),p);a.match(p.state.sources[0].id,/^src-[a-f0-9]{64}$/);});
test('first receipt adds project copy without replacing existing work',async()=>{const dest=fixture();dest.threads[0].id='unrelated';dest.sources[0].threadId='unrelated';dest.notes[0].threadId='unrelated';const p=await X.makePacket(fixture(),'project-1','p',at);const out=await X.apply(dest,await X.plan(dest,p),{},{evidence:true},id,at);a.equal(out.state.threads.length,2);a.equal(out.state.threads[0].id,'unrelated');a.equal(out.state.notes.at(-1).reviewState,'pending');});
test('incoming reviewed checkpoint must be reviewed locally',async()=>{const {b1}=await pair();a.equal(b1.notes[0].reviewState,'pending');a.ok(!O.resumePack(b1,b1.threads[0].id,at).includes('## Selected evidence\n###'));});
test('editing on another device returns to the same project',async()=>{const {a1,b1,bid}=await pair();b1.threads[0].next='Test on the phone';const p=await X.makePacket(b1,bid,'return',at),plan=await X.plan(a1,p);a.equal(plan.targetId,'project-1');a.equal(plan.rows.find(r=>r.key==='next').status,'incoming-only');const out=await X.apply(a1,plan,{next:'incoming'},{evidence:true},id,at);a.equal(out.state.threads.length,1);a.equal(out.state.threads[0].next,'Test on the phone');a.equal(out.state.notes.length,1);a.equal(out.state.notes[0].reviewState,'confirmed');});
test('both-device edits are explicit conflicts, never timestamp winners',async()=>{const {a1,b1,bid}=await pair();a1.threads[0].next='Desktop choice';b1.threads[0].next='Phone choice';const plan=await X.plan(a1,await X.makePacket(b1,bid,'return',at));a.equal(plan.rows.find(r=>r.key==='next').status,'conflict');await a.rejects(()=>X.apply(a1,plan,{},{evidence:true},id,at),/Choose/);a.equal(a1.threads[0].next,'Desktop choice');});
test('keep local conflicting value on explicit selection',async()=>{const {a1,b1,bid}=await pair();a1.threads[0].next='Desktop choice';b1.threads[0].next='Phone choice';const plan=await X.plan(a1,await X.makePacket(b1,bid,'return',at));const out=await X.apply(a1,plan,keep(plan),{evidence:true},id,at);a.equal(out.state.threads[0].next,'Desktop choice');});
test('local-only change is not overwritten by unchanged remote field',async()=>{const {a1,b1,bid}=await pair();a1.threads[0].next='Local newer';const plan=await X.plan(a1,await X.makePacket(b1,bid,'return',at));a.equal(plan.rows.find(r=>r.key==='next').status,'local-only');a.equal((await X.apply(a1,plan,{},{evidence:true},id,at)).state.threads[0].next,'Local newer');});
test('repeat round trip retains known baseline on both sides',async()=>{let {a1,b1,bid}=await pair();b1.threads[0].next='Phone edit';const p=await X.makePacket(b1,bid,'return-1',at);b1=await X.rememberExport(b1,bid,p);let plan=await X.plan(a1,p);a1=(await X.apply(a1,plan,{next:'incoming'},{evidence:true},id,at)).state;a1.threads[0].last='Desktop progress';const q=await X.makePacket(a1,'project-1','return-2',at);plan=await X.plan(b1,q);a.equal(plan.baseKnown,true);a.equal(plan.rows.find(r=>r.key==='last').status,'incoming-only');a.equal((await X.apply(b1,plan,{last:'incoming'},{evidence:true},id,at)).state.threads[0].last,'Desktop progress');});
test('unknown baseline requires two-way review rather than implied agreement',async()=>{const {a1,b1,bid}=await pair();a1.threads[0].exchangeAnchors=[];b1.threads[0].next='Phone edit';const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));a.equal(plan.baseKnown,false);a.equal(plan.rows.find(r=>r.key==='next').status,'review');});
test('tampered packet rejected',async()=>{const p=await X.makePacket(fixture(),'project-1','p',at);p.state.threads[0].next='Tamper';await a.rejects(()=>X.parse(JSON.stringify(p)),/integrity/);});
test('tampered base rejected',async()=>{const p=await X.makePacket(fixture(),'project-1','p',at);p.base.fields.next='Tamper';await a.rejects(()=>X.parse(JSON.stringify(p)),/integrity/);});
test('modified original becomes preserved source variant, not overwrite',async()=>{const {a1,b1,bid}=await pair();b1.sources[0].text+='\nNew evidence';const p=await X.makePacket(b1,bid,'p',at);const plan=await X.plan(a1,p);a.equal(plan.newRecords.sources.length,1);const out=await X.apply(a1,plan,{},{evidence:true},id,at);a.equal(out.state.sources.length,2);a.equal(out.state.sources[0].text,a1.sources[0].text);a.equal(out.state.notes[1].reviewState,'pending');});
test('new checkpoint creates a pending addition, preserves confirmed checkpoint',async()=>{const {a1,b1,bid}=await pair();b1.notes[0].statement='Changed interpretation';const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));const out=await X.apply(a1,plan,{},{evidence:true},id,at);a.equal(out.state.notes.length,2);a.equal(out.state.notes[0].statement,'Preserve original material');a.equal(out.state.notes[1].reviewState,'pending');});
test('evidence imports are optional, not automatic',async()=>{const {a1,b1,bid}=await pair();b1.sources.push(W.makeSource(b1,{title:'New',text:'New phone source',threadId:bid,speaker:'user'},id(),at));const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));const out=await X.apply(a1,plan,{},{evidence:false},id,at);a.equal(out.counts.sources,0);a.equal(out.state.sources.length,1);});
test('missing remote records do not delete local evidence',async()=>{const {a1,b1,bid}=await pair();b1.notes=[];b1.sources=[];const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));const out=await X.apply(a1,plan,{},{evidence:true},id,at);a.equal(out.state.sources.length,1);a.equal(out.state.notes.length,1);});
test('packet replay rejected',async()=>{const {b1,p}=await pair();await a.rejects(()=>X.plan(b1,p),/already applied/);});
test('stale preview rejected after workspace changes',async()=>{const {a1,b1,bid}=await pair();const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));a1.threads[0].next='Edited since preview';await a.rejects(()=>X.apply(a1,plan,keep(plan),{},id,at),/changed after/);});
test('stale export rejected after editing during preparation',async()=>{const s=fixture(),p=await X.makePacket(s,'project-1','p',at);s.threads[0].last='Changed';await a.rejects(()=>X.rememberExport(s,'project-1',p),/changed while/);});
test('malformed source reference is rejected',async()=>{const p=await X.makePacket(fixture(),'project-1','p',at);p.state.notes[0].sourceId='missing';p.snapshotHash=await X.digest(p.state);await a.rejects(()=>X.parse(JSON.stringify(p)),/evidence/);});
test('unrelated target cannot be overwritten',async()=>{const s=fixture();s.threads.push({...s.threads[0],id:'other'});const p=await X.makePacket(s,'project-1','p',at);await a.rejects(()=>X.plan(s,p,'other'),/different project/);});
test('follow-ups excluded by default and imported as separate versions only when chosen',async()=>{const {a1,b1,bid}=await pair();b1.followups.push(O.makeFollowup(b1,{threadId:bid,title:'Check tomorrow',reason:'Review result',mode:'date',date:'2026-09-27'},id(),at));const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));a.equal((await X.apply(a1,plan,{},{},id,at)).state.followups.length,0);a.equal((await X.apply(a1,plan,{},{followups:true},id,at)).state.followups.length,1);});
test('dependency IDs of other projects do not leave device',async()=>{const s=fixture();s.threads.push({...s.threads[0],id:'private-other-id',title:'Other dependency'});s.followups.push(O.makeFollowup(s,{threadId:'project-1',title:'Follow later',reason:'Dependency',mode:'resolved',dependencyId:'private-other-id'},id(),at));const p=await X.makePacket(s,'project-1','p',at);a.ok(!JSON.stringify(p).includes('private-other-id'));a.equal(p.state.followups[0].dependencyId,null);});
test('awaiting reason cannot be lost through independent field choices',async()=>{const {a1,b1,bid}=await pair();b1.threads[0].state='WAITING';b1.threads[0].waiting='A review';const plan=await X.plan(a1,await X.makePacket(b1,bid,'p',at));await a.rejects(()=>X.apply(a1,plan,{state:'incoming',waiting:'local'},{},id,at),/needs a reason/);});
test('metadata survives ordinary full backup validation',async()=>{const {a1}=await pair();a.deepEqual(W.validate(JSON.parse(JSON.stringify(a1))).threads[0].exchangeAnchors,a1.threads[0].exchangeAnchors);});
test('invalid exchange metadata rejected on backup validation',async()=>{const s=fixture();s.threads[0].exchangeAnchors=[{hash:'bad',fields:X.fields(s.threads[0])}];a.throws(()=>W.validate(s),/anchor/);});
test('oversized input rejected before parsing',async()=>{await a.rejects(()=>X.parse('x'.repeat(16000001)),/16 MB/);});
test('old project packets do not masquerade as an update packet',async()=>{await a.rejects(()=>X.parse(JSON.stringify(O.createProject(fixture(),'project-1','p',at))),/Unsupported/);});
test('encrypted project file round trip has no plaintext source',async()=>{const p=await X.makePacket(fixture(),'project-1','p',at),raw=await B.seal(JSON.stringify(p),'a long fictional passphrase');a.ok(!raw.includes('preserve the original'));a.deepEqual(await X.parse(await B.open(raw,'a long fictional passphrase')),p);await a.rejects(()=>B.open(raw,'a different long passphrase'),/Could not decrypt/);});
