/* Chromium integration, not a physical Android or microphone test.
 * FAMILY_TRACE_FILE optionally supplies private reconstructed trace fixtures; never committed here. */
const {chromium}=require('playwright'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),results=[],requests=[],errors=[];
const fixture=process.env.FAMILY_TRACE_FILE?JSON.parse(fs.readFileSync(process.env.FAMILY_TRACE_FILE,'utf8')).fixtures[0]:{id:'synthetic-newline-regression',classification:'synthetic',text:'at the boundary.\nKeep the next line'};
const exact='  '+fixture.text+'\r\nOriginal spacing.\rLast line 🙂  ';
const server=http.createServer((req,res)=>{requests.push({method:req.method,url:req.url});const u=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+u.pathname);if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403);return res.end();}try{const f=file===root?path.join(root,'index.html'):file;res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webmanifest':'application/manifest+json','.png':'image/png'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/';
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const ctx=await browser.newContext({viewport:{width:1366,height:950},permissions:['clipboard-read','clipboard-write']});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);fs.mkdirSync('test-artifacts',{recursive:true});
 const pass=x=>{results.push(x);console.log('PASS '+x);};
 const ready=()=>page.waitForFunction(()=>typeof S!=='undefined'&&!!S&&!busy);
 const go=async route=>{await page.evaluate(r=>navigate(r),route);await ready();};
 const captureReady=()=>page.waitForFunction(()=>document.querySelector('#captureForm')?.getAttribute('aria-busy')==='false');
 async function paste(text){await page.locator('#text').focus();await page.evaluate(text=>{const d=new DataTransfer();d.setData('text/plain',text);document.querySelector('#text').dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));},text);}
 try{
  await page.goto(base+'#capture');await ready();await captureReady();await paste(exact);await page.locator('#context').fill('Capture preservation test');await page.locator('#captureConsent').check();await page.evaluate(()=>flushDraft());await page.reload();await ready();await captureReady();a.equal(await page.locator('#captureRawText').inputValue(),exact);a.equal(await page.locator('#captureConsent').isChecked(),false);pass('exact draft survives reload; acceptance does not');
  await page.locator('#saveFamilyCapture').click();a.equal(await page.evaluate(()=>S.captures.length),0);pass('record save requires fresh explicit consent');
  await page.locator('#captureConsent').check();await page.locator('#saveFamilyCapture').click();await page.waitForURL('**/#sources/*');a.equal(await page.evaluate(()=>S.sources[0].text),exact);a.equal(await page.evaluate(()=>S.captures[0].sourceId),await page.evaluate(()=>S.sources[0].id));a.equal(await page.evaluate(()=>S.notes.length),0);a.equal(await page.evaluate(()=>S.sources[0].speaker),'unknown');pass('save commits exact original plus linked unreviewed capture');
  const sourceId=await page.evaluate(()=>S.sources[0].id);await go('search');await page.locator('#query').fill('Original spacing');await page.waitForTimeout(300);a.ok((await page.locator('main').innerText()).includes('Capture preservation test'));pass('saved source is retrievable by words');
  await go('capture');await captureReady();await page.locator('#text').fill('failed save must remain');await page.locator('#captureConsent').check();await page.evaluate(()=>{window.oldCommit=store.commit.bind(store);store.commit=async()=>{throw new DOMException('Simulated quota exhausted','QuotaExceededError');};});await page.locator('#saveFamilyCapture').click();await page.waitForFunction(()=>!busy&&document.querySelector('#status').textContent.includes('NOT SAVED'));a.equal(await page.locator('#text').inputValue(),'failed save must remain');a.equal(await page.evaluate(()=>S.captures.length),1);await page.evaluate(()=>{store.commit=window.oldCommit;});pass('injected workspace failure preserves draft and does not claim saved');
  await page.reload();await ready();await captureReady();a.equal(await page.locator('#text').inputValue(),'failed save must remain');a.equal(await page.locator('#captureConsent').isChecked(),false);await page.locator('#captureConsent').check();await page.evaluate(()=>{window.oldDraft=store.draft.bind(store);store.draft=async(k,v)=>{if(v===null)throw new Error('Simulated cleanup failure');return window.oldDraft(k,v);};});await page.locator('#saveFamilyCapture').click();await page.waitForFunction(()=>document.querySelector('#captureForm [role=alert]').textContent.includes('IS SAVED'));a.equal(await page.evaluate(()=>S.captures.length),2);await page.reload();await ready();await captureReady();await page.locator('#captureConsent').check();await page.locator('#saveFamilyCapture').click();await page.waitForURL('**/#sources/*');a.equal(await page.evaluate(()=>S.captures.length),2);pass('commit-success/cleanup-failure retry does not duplicate original');
  await go('capture');await captureReady();await page.locator('#text').fill('stable target check');await page.locator('#captureConsent').check();await page.locator('#saveFamilyCapture').scrollIntoViewIfNeeded();const box=await page.locator('#saveFamilyCapture').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.evaluate(()=>document.querySelector('#saveFamilyCapture').style.transform='translateX(10px)');await page.mouse.up();await page.waitForTimeout(100);a.equal(await page.evaluate(()=>S.captures.length),2);a.ok((await page.locator('#captureForm [role=alert]').innerText()).includes('target moved'));await page.evaluate(()=>document.querySelector('#saveFamilyCapture').style.transform='');pass('pointer target movement cancels action without replay');
  await page.locator('#saveFamilyCapture').focus();await page.keyboard.press('Enter');await page.waitForURL('**/#sources/*');a.equal(await page.evaluate(()=>S.captures.length),3);pass('deliberate keyboard activation remains supported');
  await go('capture');await captureReady();await page.locator('#text').fill('stale form retained');await page.locator('#captureConsent').check();const peer=await ctx.newPage();await peer.goto(base);await peer.waitForFunction(()=>!!S&&!busy);await peer.evaluate(()=>mutate('TEST_PEER','Test fixture concurrent write',s=>s.evidenceCount++));await page.locator('#saveFamilyCapture').click();await page.waitForFunction(()=>!document.querySelector('#reload').hidden);a.equal(await page.locator('#text').inputValue(),'stale form retained');a.equal(await page.evaluate(()=>S.captures.length),3);await peer.close();await page.locator('#reload').click();await captureReady();pass('stale-tab capture rejected with draft retained');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await ctx.setOffline(true);await page.reload();await ready();await captureReady();a.equal(await page.locator('#text').inputValue(),'stale form retained');await page.locator('#captureConsent').check();await page.locator('#saveFamilyCapture').click();await page.waitForURL('**/#sources/*');await page.reload();await ready();a.equal(await page.evaluate(()=>S.captures.length),4);await ctx.setOffline(false);pass('cached capture saves and retrieves offline');
  const raw=await page.evaluate(()=>JSON.stringify({format:'ContinuityBackup/2',state:S}));const second=await browser.newContext();const target=await second.newPage();await target.goto(base);await target.waitForFunction(()=>!!S&&!busy);await target.evaluate(async raw=>{const candidate=W.backup(raw);await mutate('TEST_RESTORE','Explicit test-only restore',s=>Object.assign(s,candidate),true);},raw);a.equal(await target.evaluate(id=>S.sources.find(s=>s.id===id).text,sourceId),exact);a.equal(await target.evaluate(()=>S.captures.length),4);await second.close();pass('full backup restores exact original and source linkage in separate profile');
  await go('capture');await captureReady();await page.locator('#text').fill('delayed draft flush');await page.locator('#captureConsent').check();const countBefore=await page.evaluate(()=>S.captures.length);await page.evaluate(()=>{window.realDraft=store.draft.bind(store);store.draft=async(k,v)=>{if(v!==null)await new Promise(r=>window.releaseDraft=r);return window.realDraft(k,v);};});await page.locator('#saveFamilyCapture').click();await page.waitForFunction(()=>!!window.releaseDraft);a.equal(await page.locator('#text').isDisabled(),true);a.equal(await page.locator('#saveFamilyCapture').isDisabled(),true);await page.evaluate(()=>{document.querySelector('#captureForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));store.draft=window.realDraft;window.releaseDraft();});await page.waitForURL('**/#sources/*');a.equal(await page.evaluate(()=>S.captures.length),countBefore+1);pass('in-flight draft flush locks form and rejects repeated submission');
  await page.setViewportSize({width:390,height:844});await go('capture');await captureReady();a.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-artifacts/family-capture-390.png',fullPage:true});pass('capture form fits 390px emulation (not physical Android)');
  a.deepEqual(errors,[]);a.ok(requests.every(x=>x.method==='GET'));a.ok(requests.every(x=>!x.url.includes('population')&&!x.url.includes('spacing')));pass('no script errors or capture-content network writes observed');
 }finally{fs.writeFileSync('test-artifacts/family-browser-results.json',JSON.stringify({passed:results.length,scenarios:results,fixture:{id:fixture.id,classification:fixture.classification},browser:'Chromium; local test server; no physical device',errors},null,2));await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
