'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),{webcrypto}=require('node:crypto');
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const W=require('../site/workspace-core.js'),PC=require('../site/platform-core.js'),R=require('../site/family-recovery-core.js');
test('source form rescue uses matching raw text and never revives an edited original',()=>{a.equal(R.draftBody({sourceText:'a\nb',sourceRawText:'a\r\nb'}),'a\r\nb');a.equal(R.draftBody({sourceText:'changed\nb',sourceRawText:'a\r\nb'}),'changed\nb');});
function fixture(){const state=W.empty();state.sources.push(W.makeSource(state,{title:'Original evidence',text:'  exact\r\n\r\nline 🌧',speaker:'user'},'source-1','2026-10-03T22:00:00Z'));return R.make({current:{revision:7,state},drafts:[{key:'tab:capture',value:{text:'  fragment\r\nsecond\n',type:'note',reviewed:true,context:'device trace'}}]},[PC.prepare({text:'  shared\r\noriginal  '},'share-1','2026-10-03T22:00:00Z')],{exportedAt:'2026-10-03T22:01:00Z',origin:'https://example.test',appVersion:'0.18.0-family'});}
test('rescue round trip preserves exact source, draft fields and incoming line endings',()=>{const original=fixture(),out=R.parse(JSON.stringify(original));a.deepEqual(out,original);a.equal(out.workspace.state.sources[0].text,'  exact\r\n\r\nline 🌧');a.equal(out.drafts[0].value.text,'  fragment\r\nsecond\n');a.equal(out.incoming[0].parts[0].text,'  shared\r\noriginal  ');});
test('workspace backup extraction is legacy compatible and snapshot boundary explicit',()=>{const x=fixture();a.deepEqual(W.backup(JSON.stringify(x.workspace)),x.workspace.state);a.equal(x.snapshot.atomicAcrossDatabases,false);a.equal(x.snapshot.incoming,'separate-inbox-read');});
test('restore plan only creates inert unlinked source drafts and retains raw fields as JSON',async()=>{const x=fixture(),p=await R.plan(x);a.equal(p.rows.length,2);for(const row of p.rows){a.match(row.key,/^rescue-family:[a-f0-9]{64}:/);a.equal(row.value.sourceThread,'');a.equal(row.value.sourceSpeaker,'unknown');a.equal(row.value.reviewed,undefined);a.equal(row.value.accepted,undefined);a.equal(Object.values(row.value).every(v=>typeof v==='string'),true);}a.equal(p.rows[0].value.sourceText,x.drafts[0].value.text);a.deepEqual(JSON.parse(p.rows[0].value.recoveryEvidenceJSON),x.drafts[0]);a.deepEqual(x,fixture());});
test('repeat plan creates identical IDs and values; key order does not change digest',async()=>{const first=fixture(),other=JSON.parse(JSON.stringify(first));other.drafts[0].value={context:'device trace',reviewed:true,type:'note',text:'  fragment\r\nsecond\n'};const p1=await R.plan(first),p2=await R.plan(first),p3=await R.plan(other);a.deepEqual(p1.rows,p2.rows);a.equal(p1.digest,p3.digest);a.deepEqual(p1.rows,p3.rows);});
test('changed source evidence creates a distinct rescue identity',async()=>{const x=fixture(),before=await R.plan(x);x.drafts[0].value.text+='changed';a.notEqual(before.digest,(await R.plan(x)).digest);});
test('prototype payloads are rejected everywhere before restore can open a transaction',async()=>{for(const slot of ['draft','workspace','root']){let raw=JSON.stringify(fixture());if(slot==='draft')raw=raw.replace('"text":"  fragment','"__proto__":{"polluted":true},"text":"  fragment');if(slot==='workspace')raw=raw.replace('"state":{','"state":{"constructor":{},');if(slot==='root')raw=raw.replace('{','{"prototype":{},');a.throws(()=>R.parse(raw),/Unsafe/);let opened=0;await a.rejects(R.restore({transaction(){opened++;}},JSON.parse(raw)),/Unsafe/);a.equal(opened,0);}a.equal({}.polluted,undefined);});
test('invalid content, duplicate keys, bad origins, revisions and false atomic claims reject',()=>{for(const modify of [x=>x.drafts.push(x.drafts[0]),x=>x.incoming.push(x.incoming[0]),x=>x.origin='javascript:alert(1)',x=>x.origin='https://example.test/private/path',x=>x.workspaceRevision=0,x=>x.snapshot.atomicAcrossDatabases=true,x=>x.workspace.state.sources[0].url='javascript:alert(1)',x=>x.incoming[0].status='SAVED',x=>x.drafts[0].key='',x=>x.extra=true]){const x=fixture();modify(x);a.throws(()=>R.validate(x));}});
test('plain-file byte bounds, excessive depth and too many drafts reject',()=>{a.throws(()=>R.parse(' '.repeat(R.MAX_FILE+1)),/16 MB/);const x=fixture();x.drafts=Array.from({length:1001},(_,i)=>({key:'draft:'+i,value:{text:'x'}}));a.throws(()=>R.validate(x),/1,000/);const y=fixture();let node=y.drafts[0].value;for(let i=0;i<35;i++){node.nested={};node=node.nested;}a.throws(()=>R.validate(y),/deeply nested/);});
test('malformed JSON and unsupported format reject without writes',async()=>{a.throws(()=>R.parse('{'),/valid JSON/);const x=fixture();x.format='ContinuityRecovery/99';let opened=0;await a.rejects(R.restore({transaction(){opened++;}},x),/Unsupported/);a.equal(opened,0);});
test('all original drafts retained even if their field names are unfamiliar',async()=>{const x=fixture();x.drafts.push({key:'tab:future-form',value:{unknownField:'untouched',checked:false,nested:{unfamiliar:'evidence'}}});const p=await R.plan(x);a.deepEqual(JSON.parse(p.rows[1].value.recoveryEvidenceJSON),x.drafts[1]);});
test('capture draft rescue uses exact raw endings when editor view matches, without reviving stale text',async()=>{const x=fixture();x.drafts[0].value={text:'first\nsecond\nthird',captureRawText:'first\r\nsecond\rthird'};a.equal((await R.plan(x)).rows[0].value.sourceText,'first\r\nsecond\rthird');x.drafts[0].value.text='changed\nsecond\nthird';const p=await R.plan(x);a.equal(p.rows[0].value.sourceText,'changed\nsecond\nthird');a.equal(JSON.parse(p.rows[0].value.recoveryEvidenceJSON).value.captureRawText,'first\r\nsecond\rthird');});
