/* Browser contract tests: real Chromium, IndexedDB, clipboard, offline reload.
   Native OS sharing / opening Chrome are tested as feature-detected UI contracts,
   not claims that an Android app switch occurred on the CI runner. */
const {chromium}=require('playwright');
const a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),prefix='/artificial-continuity/',results=[],requests=[];
const server=http.createServer((req,res)=>{requests.push(req.url);const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const f=path.resolve(root,url.pathname.slice(prefix.length)||'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+prefix;
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const ctx=await browser.newContext({viewport:{width:1280,height:950},permissions:['clipboard-read','clipboard-write']});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(18000);
 const pass=n=>{results.push(n);console.log('PASS '+n);};fs.mkdirSync('test-artifacts',{recursive:true});
 const nav=async r=>{await page.locator('[data-nav="'+r+'"]').click();};
 const saved=async()=>{await page.waitForFunction(()=>!busy&&document.querySelector('#status').textContent.startsWith('Saved'));};
 const target=async()=>{await nav('assistant');await page.locator('#bridgeTarget').selectOption({label:'Ship a useful test'});await page.locator('#prepareHandoff').waitFor();};
 const prepare=async()=>{const before=await page.evaluate(()=>(S.assistantRequests||[]).length);await page.locator('#prepareHandoff').click();await page.waitForFunction(n=>(S.assistantRequests||[]).length===n+1&&!busy,before);await page.waitForFunction(()=>document.querySelector('#outgoingForm')?.getAttribute('aria-busy')==='false'&&document.querySelector('#handoffText')?.value.includes(S.assistantRequests.at(-1).id));return await page.evaluate(()=>S.assistantRequests.at(-1));};
 try{
  await page.goto(base);await saved();a.ok((await page.title()).includes('0.15.0'));pass('v0.14 loads at project subpath with native storage');
  await nav('fast-intake');await page.locator('#intakeRaw').fill('Make something useful without all the forms.');await page.locator('#intakePreview').click();a.equal(await page.evaluate(()=>S.threads.length),0);a.equal(await page.locator('#intakeGoal').inputValue(),'Make something useful without all the forms.');a.equal(await page.locator('#intakeNext').inputValue(),'');pass('one-box preview makes no records and invents no next action');
  await page.locator('#intakeTitle').fill('Ship a useful test');await page.locator('#intakeNext').fill('Try the handoff');await page.locator('#intakeSave').click();await page.waitForURL('**/#project/*');await saved();a.equal(await page.evaluate(()=>S.sources[0].text),'Make something useful without all the forms.');a.equal(await page.evaluate(()=>S.notes.length),0);pass('one save creates intention and exact original source without accepted decisions');
  await page.locator('[data-action="edit-thread"]').click();await page.locator('.fill-helper summary').click();await page.locator('#fillBlock').fill('Goal: A goal from one block\nNext: Test a revision');await page.locator('#previewFill').click();a.equal(await page.locator('#applyFill').isDisabled(),true);await page.locator('.fillChoice[value="next"]').check();await page.locator('#applyFill').click();a.equal(await page.locator('#next').inputValue(),'Test a revision');a.equal(await page.locator('#objective').inputValue(),'Make something useful without all the forms.');a.equal(await page.evaluate(()=>S.threads[0].next),'Try the handoff');pass('in-editor fill previews and changes only selected unsaved form fields');
  await page.locator('#threadForm > button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});await saved();a.equal(await page.evaluate(()=>S.threads[0].next),'Test a revision');pass('filled editor saves through ordinary transactional path');
  await nav('fast-intake');await page.locator('#intakeRaw').fill('Name: Recover my draft\nGoal: Keep it\nNext: Resume');await page.locator('#intakePreview').click();await page.locator('#intakeNext').fill('Keep my edited preview');await page.evaluate(()=>flushDraft());await page.reload();await saved();await page.locator('#intakeNext').waitFor();a.equal(await page.locator('#intakeNext').inputValue(),'Keep my edited preview');pass('one-box raw input and edited preview survive reload');
  await page.locator('#intakeRaw').fill('Name: Changed raw\nGoal: Different text');await page.evaluate(()=>flushDraft());await page.reload();await saved();a.equal(await page.locator('#intakeSave').isDisabled(),true);pass('changed raw input cannot silently reuse a stale restored preview');
  page.once('dialog',d=>d.accept());await page.locator('#intakePreview').click();a.equal(await page.locator('#intakeSave').isDisabled(),false);pass('new preview explicitly re-enables save after changed input');
  // Fictional unrelated data fixture must never enter the selected project handoff.
  await page.evaluate(async()=>{await flushDraft();await mutate('TEST_FIXTURE','Fictional private fixture',s=>s.threads.push({id:'private-fixture',title:'UNRELATED_PRIVATE_SENTINEL',objective:'Private',last:'',next:'',state:'CONTINUE',open:[],waiting:'',attention:false}));});
  await target();a.ok((await page.locator('#bridgeChecks').innerText()).includes('Last position is not recorded'));pass('completeness check reports stored omissions, not invented analysis');
  const r=await prepare();let text=await page.locator('#handoffText').inputValue();a.ok(text.includes(r.id));a.ok(!text.includes('UNRELATED_PRIVATE_SENTINEL'));a.ok(text.includes('ContinuityFormReply/1'));a.equal(await page.locator('#bridgeEvidence').isChecked(),false);pass('handoff is scoped to one intention; checkpoint excerpts are opt-in');
  await page.locator('#copyHandoff').click();a.equal(await page.evaluate(()=>navigator.clipboard.readText()),text);pass('exact reviewed text copies to native clipboard');
  const download=page.waitForEvent('download');await page.locator('#downloadHandoff').click();a.equal(fs.readFileSync(await(await download).path(),'utf8'),text);pass('handoff file download preserves exact outgoing text');
  await page.locator('#handoffText').fill(text+'\nUSER EDIT');await page.evaluate(()=>flushDraft());await page.reload();await saved();await page.locator('summary', {hasText:'Prepared requests on this browser'}).click();await page.locator('[data-action="reopen-handoff"]').last().click();await page.waitForFunction(()=>document.querySelector('#outgoingForm')?.getAttribute('aria-busy')==='false');a.ok((await page.locator('#handoffText').inputValue()).endsWith('USER EDIT'));pass('prepared request and edited outgoing draft reopen after reload');
  await page.evaluate(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:undefined});});await page.locator('#shareHandoff').click();a.ok((await page.locator('#handoffStatus').innerText()).includes('unavailable'));pass('unsupported native sharing has a copy/download fallback');
  await page.evaluate(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.sharedFixture=data;throw new DOMException('User cancelled','AbortError');}});});await page.locator('#shareHandoff').click();a.ok((await page.locator('#handoffStatus').innerText()).includes('cancelled'));a.ok((await page.evaluate(()=>window.sharedFixture.text)).endsWith('USER EDIT'));pass('share uses only reviewed text and handles cancellation without changing state');
  const rep={format:'ContinuityFormReply/1',requestId:r.id,fields:{next:'Run a focused field test',objective:'Do not select this change'},explanation:'Fictional test suggestion'};
  await page.locator('#replyRaw').fill(JSON.stringify(rep));await page.locator('#reviewReply').click();a.equal(await page.locator('#applyReply').isDisabled(),true);a.equal(await page.locator('.replyField:checked').count(),0);a.equal(await page.evaluate(()=>S.threads[0].next),'Test a revision');pass('reply preview selects nothing and changes no saved fields');
  await page.locator('.replyField[value="next"]').check();await page.locator('#applyReply').click();await page.waitForURL('**/#project/*');await saved();a.equal(await page.evaluate(()=>S.threads[0].next),'Run a focused field test');a.equal(await page.evaluate(()=>S.threads[0].objective),'Make something useful without all the forms.');a.equal(await page.evaluate(()=>S.sources[0].text),'Make something useful without all the forms.');pass('only explicitly selected field applies; original sources and other fields stay');
  await target();await page.locator('#replyRaw').fill(JSON.stringify(rep));await page.locator('#reviewReply').click();a.ok((await page.locator('#replyForm [role=alert]').innerText()).includes('already applied'));pass('same response cannot replay after application');
  const r2=await prepare();await page.evaluate(async()=>{await mutate('TEST_NEWER','Simulate newer user edit',s=>s.threads[0].next='Newer user choice');});await page.locator('#replyRaw').fill(JSON.stringify({...rep,requestId:r2.id}));await page.locator('#reviewReply').click();a.ok((await page.locator('#replyForm [role=alert]').innerText()).includes('changed'));a.equal(await page.evaluate(()=>S.threads[0].next),'Newer user choice');pass('stale response cannot overwrite newer intention content');
  const r3=await prepare();await page.locator('#replyRaw').fill(JSON.stringify({...rep,requestId:r3.id,commands:['delete everything']}));await page.locator('#reviewReply').click();a.ok((await page.locator('#replyForm [role=alert]').innerText()).includes('unsupported'));pass('out-of-contract commands are rejected');
  await page.locator('#replyRaw').fill(JSON.stringify({...rep,requestId:r3.id,fields:{next:'<img src=x onerror="window.pwned=true">'}}));await page.locator('#reviewReply').click();a.equal(await page.locator('#replyPreview img').count(),0);a.equal(await page.evaluate(()=>window.pwned),undefined);pass('model markup renders as text, never executable DOM');
  await nav('open-separately');await page.locator('#copyAppAddress').click();a.equal(await page.evaluate(()=>navigator.clipboard.readText()),base);a.ok((await page.locator('main').innerText()).includes('different browser may start with an empty'));pass('separate-browser helper copies only clean app URL and warns about storage separation');
  await page.setViewportSize({width:390,height:844});await target();await page.locator('#replyRaw').fill(JSON.stringify({...rep,requestId:r3.id,fields:{next:'A reviewed next action'}}));await page.locator('#reviewReply').click();a.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-artifacts/handoff-mobile.png',fullPage:true});pass('390px handoff and field-diff layout has no horizontal overflow');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await page.evaluate(()=>flushDraft());await ctx.setOffline(true);await page.reload();await saved();await page.locator('#replyRaw').waitFor();a.ok((await page.locator('#replyRaw').inputValue()).includes(r3.id));pass('handoff form and pending reply remain usable after offline reload');await ctx.setOffline(false);
  a.ok(requests.every(u=>!u.includes('PRIVATE_SENTINEL')&&!u.includes('Ship%20a')));a.deepEqual(errors,[]);pass('no private handoff content in HTTP requests and no browser errors');
 }catch(err){fs.writeFileSync('test-artifacts/handoff-debug.json',JSON.stringify(await page.evaluate(async()=>({route,hash:location.hash,forms:[...document.forms].map(f=>({id:f.id,busy:f.getAttribute('aria-busy')})),drafts:await draftRows()})).catch(()=>({})),null,2));await page.screenshot({path:'test-artifacts/handoff-failure.png',fullPage:true}).catch(()=>{});throw err;}
 finally{fs.writeFileSync('test-artifacts/handoff-results.json',JSON.stringify({passed:results.length,scenarios:results,errors},null,2));await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
