const {test}=require('node:test'),a=require('node:assert/strict');
const W=require('../site/workspace-core.js');require('../site/operations-core.js');const H=require('../site/handoff-core.js');
function seed(){const s=W.empty();s.threads=[{id:'project',title:'Own project',objective:'Build it',last:'Draft',next:'Check',open:['Why?'],state:'CONTINUE',waiting:'',attention:false},{id:'secret',title:'Unrelated PRIVATE_SENTINEL',objective:'Hidden',last:'',next:'',open:[],state:'CONTINUE',waiting:'',attention:false}];s.assistantRequests=[H.request(s,'project','r1','2026-09-26')];return s;}
const reply=(f={next:'Test it'})=>({format:'ContinuityFormReply/1',requestId:'r1',fields:f});
test('plain intake preserves complete text without inventing next steps',()=>{const p=H.parseText('A rough thought\nNeeds room.');a.equal(p.raw,'A rough thought\nNeeds room.');a.equal(p.fields.objective,p.raw);a.equal(p.fields.next,undefined);a.equal(p.mode,'plain');});
test('labelled intake fills all seven fields',()=>{const p=H.parseText('Name: Ship\nGoal: Help\nLast: Discussed\nNext: Test\nQuestions:\n- How?\n- Who?\nState: continue later\nWaiting:');a.deepEqual(p.fields,{title:'Ship',objective:'Help',last:'Discussed',next:'Test',open:['How?','Who?'],state:'CONTINUE',waiting:''});});
test('duplicate label rejected rather than silently overwritten',()=>a.throws(()=>H.parseText('Goal: A\nGoal: B'),/Repeated/));
test('intake preserves unlabelled text and discloses omissions',()=>{const p=H.parseText('Intro\nGoal: A');a.ok(p.warnings.length);a.equal(p.raw,'Intro\nGoal: A');});
test('oversized and binary intake rejected',()=>{a.throws(()=>H.parseText('x'.repeat(16001)));a.throws(()=>H.parseText('x\0y'));});
test('invalid state rejected',()=>a.throws(()=>H.parseText('State: Delete everything')));
test('multiple questions and markup retained as inert data',()=>a.equal(H.parseText('Goal: <img onerror=alert(1)>').fields.objective,'<img onerror=alert(1)>'));
test('empty input rejected',()=>a.throws(()=>H.parseText('   ')));
test('JSON reply and single code fence accepted',()=>{a.deepEqual(H.parseReply('```json\n'+JSON.stringify(reply())+'\n```'),reply());});
test('extra text and multiple fences rejected',()=>a.throws(()=>H.parseReply('Analysis\n'+JSON.stringify(reply()))));
test('reply cannot carry executable commands',()=>a.throws(()=>H.parseReply(JSON.stringify({...reply(),commands:['send-email']})),/unsupported/));
test('reply cannot edit sources or arbitrary properties',()=>a.throws(()=>H.parseReply(JSON.stringify(reply({sources:[]}))),/Unsupported/));
test('prototype injection rejected',()=>a.throws(()=>H.parseReply('{"format":"ContinuityFormReply/1","requestId":"r1","fields":{"__proto__":{"a":1}}}')));
test('oversize reply rejected',()=>a.throws(()=>H.parseReply('x'.repeat(64001))));
test('reply question list and state validated',()=>{a.throws(()=>H.parseReply(JSON.stringify(reply({open:'wrong'}))));a.throws(()=>H.parseReply(JSON.stringify(reply({state:'DELETE'}))));});
test('unknown request never creates a target',()=>a.throws(()=>H.preview(seed(),{...reply(),requestId:'unknown'}),/matching/));
test('stale target blocked, other project changes do not block',()=>{const s=seed();s.threads[1].next='Changed';a.equal(H.preview(s,reply()).changes.length,1);s.threads[0].next='Newer';a.throws(()=>H.preview(s,reply()),/changed/);});
test('only selected proposed fields change; originals and unrelated project stay',()=>{const s=seed(),out=H.applyReply(s,reply({next:'Test',objective:'New idea'}),['next']);a.equal(out.threads[0].next,'Test');a.equal(out.threads[0].objective,s.threads[0].objective);a.deepEqual(out.sources,s.sources);a.deepEqual(out.threads[1],s.threads[1]);a.equal(s.assistantRequests[0].status,'OPEN');});
test('request consumed and cannot replay',()=>a.throws(()=>H.preview(H.applyReply(seed(),reply(),['next']),reply()),/already applied/));
test('empty, fabricated, and duplicate selections rejected',()=>{for(const sel of [[],['state'],['next','next']])a.throws(()=>H.applyReply(seed(),reply(),sel));});
test('waiting state requires a recorded reason',()=>{a.throws(()=>H.applyReply(seed(),reply({state:'WAITING'}),['state']),/reason/);a.equal(H.applyReply(seed(),reply({state:'WAITING',waiting:'Response'}),['state','waiting']).threads[0].waiting,'Response');});
test('packet contains only selected project, not unrelated title',()=>{const s=seed(),text=H.packet(s,s.assistantRequests[0]);a.ok(text.includes('Own project'));a.ok(!text.includes('PRIVATE_SENTINEL'));a.ok(text.includes('ContinuityFormReply/1'));});
test('evidence is opt-in; pending checkpoints excluded',()=>{const s=seed();s.notes=[{threadId:'project',reviewState:'pending',statement:'PENDING_SENTINEL',kind:'decision',quote:'PENDING_SENTINEL'},{threadId:'project',reviewState:'confirmed',statement:'ACCEPTED_SENTINEL',kind:'decision',quote:'selected quote',sourceId:'s1',start:1,end:1}];a.ok(!H.packet(s,s.assistantRequests[0]).includes('ACCEPTED_SENTINEL'));const text=H.packet(s,s.assistantRequests[0],'',true);a.ok(text.includes('ACCEPTED_SENTINEL'));a.ok(!text.includes('PENDING_SENTINEL'));});
test('local completeness check reports missing fields, not inferred truths',()=>{const s=seed();s.threads[0].next='';a.deepEqual(H.report(s,'project').missing,['Next action is not recorded.']);});
test('clean app address removes both query and fragment data',()=>a.equal(H.cleanAppURL('https://example.com/app/index.html?secret=foo#project/bar'),'https://example.com/app/'));
test('non-web schemes rejected',()=>a.throws(()=>H.cleanAppURL('javascript:alert(1)')));
test('request collection rejects duplicates, wrong targets and malformed baseline',()=>{const s=seed();s.assistantRequests.push(s.assistantRequests[0]);a.throws(()=>H.checkRequests(s));const b=seed();b.assistantRequests[0].base={next:'only'};a.throws(()=>H.checkRequests(b));});
