/* Native Chromium tests, including the actual project subpath and offline worker. */
const {chromium}=require('playwright'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),prefix='/artificial-continuity/',results=[],requests=[];let updatedWorker=false;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');requests.push({method:req.method,path:url.pathname,query:url.search});if(!url.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const name=url.pathname.slice(prefix.length)||'index.html',f=path.resolve(root,name);if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{let body=fs.readFileSync(f);if(name==='service-worker.js'&&updatedWorker)body=Buffer.concat([body,Buffer.from('\n// New bytes for the explicit-update regression scenario.\n')]);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.webmanifest':'application/manifest+json','.png':'image/png'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(body);}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+prefix;const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{} )});const context=await browser.newContext({viewport:{width:1280,height:900},permissions:['clipboard-read','clipboard-write']});let page=await context.newPage();const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);const pass=name=>{results.push(name);console.log('PASS '+name);};fs.mkdirSync('test-artifacts',{recursive:true});
 async function nav(name){await page.locator('[data-nav="'+name+'"]').click();}
 async function newThread(title){await nav('intentions');await page.locator('main [data-action="new-thread"]').click();await page.locator('#title').fill(title);await page.locator('#objective').fill('Operational test goal');await page.locator('#next').fill('Review the evidence');await page.locator('#threadForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});}
 async function newFollowup(title,mode,thread,dependency){await nav('followups');await page.locator('[data-action="new-followup"]').click();await page.locator('#followTitle').fill(title);await page.locator('#followThread').selectOption({label:thread});await page.locator('#followMode').selectOption(mode);if(mode==='date')await page.locator('#followDate').fill(await page.evaluate(()=>OperationalCore.today()));else await page.locator('#followDependency').selectOption({label:dependency});await page.locator('#followForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});}
 try{
  await page.goto(base);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));a.ok((await page.title()).includes(require('../site/operations-core.js').APP_VERSION));pass('current release boots at the real GitHub Pages subpath');
  await newThread('Operational project');await newThread('Dependency project');pass('create real intentions with extended schema');
  await nav('sources');await page.locator('[data-action="bulk"]').click();await page.locator('#batchThread').selectOption({label:'Operational project'});await page.locator('#batchFiles').setInputFiles([{name:'Decision.txt',mimeType:'text/plain',buffer:Buffer.from('User: We decided to keep original wording.\nSecret unselected text.\nEmail: person@example.org')},{name:'Duplicate.md',mimeType:'text/markdown',buffer:Buffer.from('User: We decided to keep original wording.\nSecret unselected text.\nEmail: person@example.org')},{name:'Other.md',mimeType:'text/markdown',buffer:Buffer.from('A separate note.') }]);await page.waitForFunction(()=>document.querySelector('#batchStatus').textContent.startsWith('Preview:'));a.equal(await page.locator('.batchChoice:checked').count(),2);a.equal(await page.evaluate(()=>S.sources.length),0);await page.locator('#batchSave').click();await page.waitForFunction(()=>typeof S!=='undefined'&&S.sources.length===2);pass('batch preview skips exact duplicates and commits selected originals');
  const sid=await page.evaluate(()=>S.sources.find(x=>x.title==='Decision').id);await page.locator('[data-action="source"][data-id="'+sid+'"]').click();await page.locator('[data-action="checkpoint"][data-line="1"]').click();await page.locator('#statement').fill('Keep original wording.');await page.locator('#reviewed').check();await page.locator('#noteForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});pass('batch source becomes a reviewed checkpoint with verbatim evidence');
  const tid=await page.evaluate(()=>S.threads.find(x=>x.title==='Operational project').id);await nav('intentions');await page.locator('[data-action="pack"][data-id="'+tid+'"]').click();a.ok((await page.locator('#packText').inputValue()).includes('Keep original wording.'));await page.locator('details summary').click();await page.locator('.packChoice').uncheck();a.ok(!(await page.locator('#packText').inputValue()).includes('Keep original wording.'));await page.locator('.packChoice').check();await page.locator('#packText').fill((await page.locator('#packText').inputValue())+'\nContact person@example.org');await page.waitForFunction(()=>document.querySelector('#privacyWarning').textContent.includes('Email-like'));await page.locator('[data-action="copy-pack"]').click();a.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('Contact person@example.org'));a.equal(await page.evaluate(()=>S.sources.find(x=>x.title==='Decision').text.split('\n')[0]),'User: We decided to keep original wording.');pass('selective handoff and sensitive-pattern warning leave source unchanged');
  await newFollowup('Due now','date','Operational project');await nav('now');await page.getByRole('heading',{name:'Due now',exact:true}).waitFor();a.ok(await page.getByRole('heading',{name:'Ready to revisit · 1',exact:true}).isVisible());await page.locator('article').filter({has:page.getByRole('heading',{name:'Due now',exact:true})}).locator('[data-action="complete-followup"]').click();await page.waitForFunction(()=>!busy&&S.followups.find(f=>f.title==='Due now')?.state==='DONE'&&document.querySelector('#status').textContent.startsWith('Saved'));await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));a.equal(await page.getByRole('heading',{name:'Due now',exact:true}).count(),0);pass('date follow-up is real, explicitly completed, and persists across reload');
  await newFollowup('After dependency','resolved','Operational project','Dependency project');await nav('now');a.equal(await page.getByRole('heading',{name:'After dependency',exact:true}).count(),0);await nav('intentions');const dep=await page.evaluate(()=>S.threads.find(x=>x.title==='Dependency project').id);await page.locator('[data-action="edit-thread"][data-id="'+dep+'"]').click();await page.locator('#state').selectOption('RESOLVED');await page.locator('#threadForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});await nav('now');await page.getByRole('heading',{name:'After dependency',exact:true}).waitFor();a.equal(await page.evaluate(id=>S.threads.find(x=>x.id===id).state,tid),'CONTINUE');pass('dependency resolution makes a follow-up ready without executing it');
  await nav('intentions');await page.locator('[data-action="project-export"][data-id="'+tid+'"]').click();a.ok(await page.getByText(/FULL original source text/).isVisible());const downloadPromise=page.waitForEvent('download');await page.locator('#downloadProject').click();const download=await downloadPromise,packetBytes=fs.readFileSync(await download.path()),packet=JSON.parse(packetBytes);a.equal(packet.format,'ContinuityProject/1');a.equal(packet.state.threads.length,1);a.equal(packet.state.sources.length,2);a.ok(packetBytes.toString().includes('Secret unselected text.'));await page.locator('[data-action="close"]').click();pass('full project export explicitly includes originals and excludes unrelated intentions');
  await nav('transfer');await page.locator('#projectFile').setInputFiles({name:'project.json',mimeType:'application/json',buffer:packetBytes});await page.locator('#addProject:enabled').waitFor();a.equal(await page.evaluate(()=>S.threads.length),2);await page.locator('#addProject').click();await page.locator('#packText').waitFor();a.equal(await page.evaluate(()=>S.threads.length),3);a.ok(!(await page.locator('#packText').inputValue()).includes('Keep original wording.'));a.ok((await page.locator('#packText').inputValue()).includes('await review'));pass('project import appends without overwrite and quarantines imported checkpoints');
  const importedSource=await page.evaluate(()=>S.sources.find(x=>x.originSourceId===S.sources.find(y=>y.title==='Decision'&&!y.originSourceId).id).id);await nav('sources');await page.locator('[data-action="source"][data-id="'+importedSource+'"]').click();await page.locator('[data-action="confirm-import"]').click();a.equal(await page.locator('#importReviewed').isChecked(),false);await page.locator('#importReviewed').check();await page.locator('#importNoteForm button.primary').click();await page.waitForSelector('#dialog',{state:'hidden'});const importedId=await page.evaluate(()=>S.threads.find(x=>x.importedPacketId).id);await nav('intentions');await page.locator('[data-action="pack"][data-id="'+importedId+'"]').click();a.ok((await page.locator('#packText').inputValue()).includes('Keep original wording.'));pass('imported evidence enters handoff only after explicit local review');
  await nav('transfer');await page.locator('#projectFile').setInputFiles({name:'same.json',mimeType:'application/json',buffer:packetBytes});await page.locator('#addProject:enabled').waitFor();await page.locator('#addProject').click();await page.waitForFunction(()=>document.querySelector('#projectPreview').textContent.includes('already imported'));a.equal(await page.evaluate(()=>S.threads.length),3);pass('duplicate project packet is rejected without mutation');
  await nav('sources');await page.locator('[data-action="add-source"]').click();await page.locator('#sourceTitle').fill('Lost-tab draft');await page.locator('#sourceText').fill('A recoverable thought from another tab.');await page.waitForFunction(()=>document.querySelector('dialog .draft-status').textContent.includes('Draft saved'));await page.locator('[data-action="close"]').click();const prior=page;page=await context.newPage();page.setDefaultTimeout(20000);await page.goto(base+'#device');await page.getByRole('heading',{name:'Lost-tab draft',exact:true}).waitFor();await page.locator('article').filter({has:page.getByRole('heading',{name:'Lost-tab draft',exact:true})}).locator('[data-action="recover-draft"]').click();await page.waitForFunction(()=>document.querySelector('#sourceText')?.value==='A recoverable thought from another tab.');await page.locator('#sourceForm button.primary').click();await page.getByRole('heading',{name:'Lost-tab draft',exact:true}).waitFor();await prior.close();pass('draft rescue recovers another tab’s unsaved form into a source');
  await nav('sources');await page.locator('[data-action="add-source"]').click();await page.locator('#sourceTitle').fill('Long source');await page.locator('#sourceText').fill(Array.from({length:1005},(_,i)=>'Line '+(i+1)).join('\n'));await page.locator('#sourceForm button.primary').click();await page.locator('#jumpLine').fill('901');await page.locator('#jumpSource').click();a.equal(await page.locator('.source-line .ln').first().textContent(),'901');a.equal(await page.locator('.source-line span').nth(1).textContent(),'Line 901');await page.setViewportSize({width:390,height:844});a.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-artifacts/v012-mobile-source.png',fullPage:true});await page.setViewportSize({width:1280,height:900});pass('long-source navigation and 390px mobile layout');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.goto(base+'#capture');await page.locator('#text').fill('Captured while completely offline.');await page.locator('#captureForm button.primary').click();await page.getByText('Captured while completely offline.',{exact:true}).waitFor();await page.reload();await page.getByText('Captured while completely offline.',{exact:true}).waitFor();await context.setOffline(false);pass('actual service worker reload and native IndexedDB capture work offline');
  await page.locator('#text').fill('Draft survives reviewed update.');await page.waitForFunction(()=>document.querySelector('main .draft-status').textContent.includes('Draft saved'));updatedWorker=true;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await page.locator('#applyUpdate:visible').waitFor();a.equal(await page.locator('#text').inputValue(),'Draft survives reviewed update.');page.once('dialog',d=>d.accept());await page.locator('#applyUpdate').click();await page.waitForFunction(()=>document.querySelector('#text')?.value==='Draft survives reviewed update.');pass('app update waits for explicit approval and preserves an unfinished draft');
  await nav('followups');await page.screenshot({path:'test-artifacts/v012-followups.png',fullPage:true});await nav('device');await page.screenshot({path:'test-artifacts/v012-device-drafts.png',fullPage:true});
  a.deepEqual(errors,[]);a.ok(requests.every(r=>r.method==='GET'));a.ok(!requests.some(r=>/Secret|Captured|person%40/.test(r.query)));pass('no uncaught errors or content-bearing network writes');
  fs.writeFileSync('test-artifacts/operations-results.json',JSON.stringify({passed:results.length,scenarios:results},null,2));
 }catch(e){console.error(e);await page.screenshot({path:'test-artifacts/v012-failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('test-artifacts/operations-failure.txt',e.stack+'\n'+errors.join('\n'));throw e;}
 finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
