const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../site/platform-core.js'),W=require('../site/workspace-core.js');
const at='2026-09-26T12:00:00.000Z',pkt=x=>P.prepare(x,'incoming-1',at);let seq=0;const uid=()=>`test-${++seq}`;
const state=()=>W.empty();
test('incoming text retains whitespace and markup literally',()=>{const s=' <b>Do not execute</b>\n\n';a.equal(pkt({text:s}).parts[0].text,s);});
test('link-only intake preserves a reference and never fetches',()=>{a.equal(pkt({url:'https://example.test/a'}).parts[0].url,'https://example.test/a');});
test('unsafe URL scheme is rejected',()=>a.throws(()=>pkt({text:'test',url:'javascript:alert(1)'})));
test('embedded URL credentials rejected',()=>a.throws(()=>pkt({url:'https://name:secret@example.test/'})));
test('title-only share is accepted',()=>a.equal(pkt({title:'Remember this'}).parts[0].text,'Remember this'));
test('empty incoming share is rejected',()=>a.throws(()=>pkt({})));
test('binary null rejected before storage',()=>a.throws(()=>pkt({text:'a\0b'})));
test('UTF-8 byte limit, not only character count',()=>a.throws(()=>pkt({text:'🧡'.repeat(250001)})));
test('nontext files rejected',()=>a.throws(()=>pkt({files:[{name:'photo.png',text:'not text'}]})));
test('too many files rejected',()=>a.throws(()=>pkt({files:Array.from({length:11},()=>({name:'a.txt',text:'a'}))})));
test('total transfer limit enforced',()=>a.throws(()=>pkt({files:Array.from({length:5},()=>({name:'a.txt',text:'a'.repeat(900000)}))})));
test('several files preserve names and bodies',()=>{const p=pkt({files:[{name:'a.txt',text:'first'},{name:'b.md',text:'# second'}]});a.equal(p.parts[1].text,'# second');a.equal(p.parts[1].filename,'b.md');});
test('pending share does not mutate workspace',()=>{const s=state(),before=JSON.stringify(s);pkt({text:'candidate'});a.equal(JSON.stringify(s),before);});
test('source import is a pure preview with unknown attribution',()=>{const s=state(),r=P.importInto(s,pkt({text:'The original.'}),'source',null,W.makeSource,uid,at);a.equal(s.sources.length,0);a.equal(r.state.sources[0].speaker,'unknown');a.equal(r.state.notes.length,0);a.equal(r.state.sources[0].incomingShareId,'incoming-1');W.validate(r.state);});
test('selected source link is retained',()=>{const s=state();s.threads.push({id:'t',title:'Goal',objective:'',next:'',last:'',open:[],waiting:'',state:'CONTINUE'});const r=P.importInto(s,pkt({text:'evidence'}),'source','t',W.makeSource,uid,at);a.equal(r.state.sources[0].threadId,'t');});
test('unknown intention fails instead of becoming a broken link',()=>a.throws(()=>P.importInto(state(),pkt({text:'a'}),'source','missing',W.makeSource,uid,at)));
test('exact duplicates skip without relinking',()=>{const s=state();s.sources.push(W.makeSource(s,{title:'Original',text:'same',url:'',threadId:null,speaker:'user'},uid(),at));const r=P.importInto(s,pkt({text:'same'}),'source',null,W.makeSource,uid,at);a.equal(r.skipped,1);a.equal(r.added,0);a.deepEqual(r.state.sources,s.sources);});
test('repeated packet cannot replay after a committed receipt',()=>{const s=state();s.events.push({id:uid(),type:'SHARED_CONTENT_SAVED',reason:'Incoming share incoming-1',at});a.throws(()=>P.importInto(s,pkt({text:'a'}),'source',null,W.makeSource,uid,at));});
test('capture import has safe length and status',()=>{const r=P.importInto(state(),pkt({text:'Keep this'}),'capture',null,W.makeSource,uid,at);a.equal(r.state.captures[0].status,'UNPROCESSED');W.validate(r.state);});
test('long incoming text must use a source, not truncated capture',()=>a.throws(()=>P.importInto(state(),pkt({text:'a'.repeat(20001)}),'capture',null,W.makeSource,uid,at)));
test('invalid packet/parts fail before state change',()=>{a.throws(()=>P.validate({format:'OTHER'}));a.throws(()=>P.validate({...pkt({text:'a'}),parts:[{title:'x',text:'bad',url:'file:///secret'}]}));});
test('manifest keeps stable ID, standalone launch and POST share intake',()=>{const m=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../site/manifest.webmanifest')));a.equal(m.id,'./');a.equal(m.scope,'./');a.equal(m.display,'standalone');a.equal(m.share_target.method,'POST');a.equal(m.share_target.action,'./share-in');a.ok(!JSON.stringify(m.share_target).includes('GET'));});
test('icons match manifest pixel dimensions',()=>{for(const n of [192,512]){const b=fs.readFileSync(path.resolve(__dirname,`../site/icon-${n}.png`));a.equal(b.readUInt32BE(16),n);a.equal(b.readUInt32BE(20),n);}});
test('new scripts are in the shell and pinned offline cache',()=>{const index=fs.readFileSync(path.resolve(__dirname,'../site/index.html'),'utf8'),sw=fs.readFileSync(path.resolve(__dirname,'../site/service-worker.js'),'utf8');for(const f of ['platform-core.js','share-inbox.js','platform.js','platform.css']){a.ok(index.includes(f+'?v=0.18.0'));a.ok(sw.includes(f));}a.ok(sw.includes("const RELEASE='0.18.0'"));});
