/* Real Chromium + IndexedDB + service-worker POST tests. Not a native Android launcher test. */
const {chromium}=require('playwright'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),prefix='/artificial-continuity/',results=[],serverRequests=[];
const server=http.createServer((req,res)=>{serverRequests.push({method:req.method,url:req.url});const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/launcher'){res.writeHead(200,{'Content-Type':'text/html'});res.end(`<form method="post" enctype="multipart/form-data" action="${prefix}share-in"><input name="title" value="Launcher note"><textarea name="text">PRIVATE_LAUNCHER_SENTINEL</textarea><button>Share locally</button></form>`);return;}
 if(!u.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const f=path.resolve(root,u.pathname.slice(prefix.length)||'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+prefix;
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const ctx=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);
 const pass=t=>{results.push(t);console.log('PASS '+t);};const saved=()=>page.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy&&document.querySelector('#status').textContent.startsWith('Saved'));const nav=(r,id=null)=>page.evaluate(([r,id])=>navigate(r,id),[r,id]);fs.mkdirSync('test-artifacts',{recursive:true});
 async function post(input){return page.evaluate(async input=>{const f=new FormData();for(const [k,v] of Object.entries(input))f.append(k,v);const r=await fetch('./share-in',{method:'POST',body:f});return {status:r.status,text:await r.text()};},input);}
 try{
  await page.goto(base+'#install');await saved();await page.locator('#platformHealth .device-state').first().waitFor();a.ok((await page.title()).includes(require('../site/operations-core.js').APP_VERSION));pass('installation deep link loads after startup barrier');
  const m=await page.evaluate(()=>fetch('./manifest.webmanifest').then(r=>r.json()));a.equal(m.display,'standalone');a.equal(m.id,'./');a.equal(m.share_target.method,'POST');a.equal(m.shortcuts.length,4);pass('phone/desktop manifest retains stable identity and four app shortcuts');
  a.ok((await page.locator('main').innerText()).includes('not a separately compiled Android APK'));a.ok((await page.locator('main').innerText()).includes('Before moving out of the embedded browser'));pass('install instructions distinguish PWA from native binary and warn about existing data');
  await page.locator('#copyPlatformURL').click();a.equal(await page.evaluate(()=>navigator.clipboard.readText()),base);pass('installation helper copies only a clean URL');
  await page.locator('#focusControl').click();a.equal(await page.locator('aside').isVisible(),false);await page.reload();await saved();a.equal(await page.locator('aside').isVisible(),false);await page.locator('#focusControl').click();pass('desktop focus layout survives restart and remains reversible');
  await page.keyboard.press('Control+Shift+K');await page.locator('#commandQuery').waitFor();await page.locator('#commandQuery').fill('Quick capture');await page.keyboard.press('Enter');await page.locator('#captureForm').waitFor();await page.waitForFunction(()=>document.querySelector('#captureForm')?.getAttribute('aria-busy')==='false');pass('command shortcut opens palette and Enter opens the selected function');
  await page.locator('#text').fill('Desktop shortcut capture');await page.locator('#captureConsent').check();await page.keyboard.press('Control+Enter');await saved();await page.waitForFunction(()=>S.captures.some(c=>c.text==='Desktop shortcut capture'));pass('keyboard submission saves through normal transactional capture path');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);pass('real service worker controls the app before share intake');
  let r=await post({title:'Incoming test',text:'PRIVATE_SHARE_SENTINEL\n<b>literal text</b>'});a.equal(r.status,200);a.equal(await page.evaluate(()=>S.sources.length),1);const rows=await page.evaluate(()=>PI.list());a.equal(rows.length,1);a.equal(rows[0].status,'PENDING');pass('POST share persists in native IndexedDB without changing workspace');
  a.equal(serverRequests.filter(r=>r.method==='POST').length,0);a.ok(serverRequests.every(r=>!r.url.includes('PRIVATE_SHARE')));pass('controlled share POST never reaches the static host or its URL log');
  await nav('incoming');await page.locator('[data-action="review-share"]').click();await page.locator('#saveIncoming').waitFor();a.equal(await page.locator('.inbox-pre b').count(),0);a.ok((await page.locator('.inbox-pre').innerText()).includes('<b>literal text</b>'));pass('incoming markup displayed literally, not as active HTML');
  await page.locator('#saveIncoming').click();await page.waitForURL('**/#sources');await saved();a.equal(await page.evaluate(id=>S.sources.find(s=>s.incomingShareId===id).speaker,rows[0].id),'unknown');a.equal(await page.evaluate(()=>S.notes.length),0);a.equal(await page.evaluate(id=>S.sources.find(s=>s.incomingShareId===id).text,rows[0].id),rows[0].parts[0].text);pass('explicit source save preserves reviewed transport text and creates no reviewed decisions');
  await nav('incoming');await page.locator('[data-action="review-share"]').click();await page.locator('#saveIncoming').click();a.ok((await page.locator('#incomingSaveStatus').innerText()).includes('already saved'));pass('committed share receipt blocks duplicate replay');
  await nav('incoming');await page.locator('#incomingFiles').setInputFiles({name:'desktop.md',mimeType:'text/markdown',buffer:Buffer.from('# Imported desktop text')});await page.getByRole('heading',{name:'desktop.md',exact:true}).waitFor();a.equal(await page.evaluate(()=>S.sources.length),2);pass('desktop file input stages a local review item without auto-import');
  await page.locator('[data-action="review-share"]').first().click();await page.locator('#incomingMode').selectOption('capture');await page.locator('#saveIncoming').click();await page.waitForURL('**/#capture');await saved();a.ok(await page.evaluate(()=>S.captures.some(c=>c.text==='# Imported desktop text')));pass('incoming text can become a quick capture after explicit selection');
  r=await post({text:'bad',url:'javascript:alert(1)'});a.equal(r.status,400);a.ok(r.text.includes('not a safe HTTP(S)'));pass('unsafe incoming URLs rejected without execution');
  r=await post({text:'x'.repeat(1000001)});a.equal(r.status,400);pass('oversized incoming text rejected by worker');
  const count=await page.evaluate(async()=>(await PI.list()).length);r=await page.evaluate(async()=>{const f=new FormData();f.append('files',new File(['png'],'bad.png',{type:'image/png'}));const r=await fetch('./share-in',{method:'POST',body:f});return r.status;});a.equal(r,400);a.equal(await page.evaluate(async()=>(await PI.list()).length),count);pass('unsupported file rejection leaves the existing inbox unchanged');
  await ctx.setOffline(true);r=await post({title:'Offline share',text:'PRIVATE_OFFLINE_SENTINEL'});a.equal(r.status,200);await nav('incoming');await page.reload();await saved();await page.getByRole('heading',{name:'Offline share',exact:true}).waitFor();pass('incoming POST and inbox reload work offline after shell activation');await ctx.setOffline(false);
  // A top-level form submission exercises navigation interception from outside app scope.
  await page.goto(origin+'/launcher');await page.getByRole('button',{name:'Share locally'}).click();await page.waitForURL('**/#shared');await saved();await page.getByRole('heading',{name:'Launcher note',exact:true}).waitFor();a.equal(serverRequests.filter(r=>r.method==='POST').length,0);pass('real POST navigation enters installed-app scope and redirects to local review inbox');
  await page.evaluate(async()=>{await mutate('TEST_FIXTURE','Fictional scale and project data',s=>{s.threads.push({id:'project-platform',title:'Platform test project',objective:'Test device workflows',last:'',next:'Review evidence',open:[],waiting:'',state:'CONTINUE',attention:false});for(let i=0;i<75;i++)s.sources.push(W.makeSource(s,{title:'Fixture '+i,text:'Fixture source body '+i,url:'',threadId:i%2?'project-platform':null,speaker:'unknown'},uid(),now()));});});
  await nav('sources');a.equal(await page.locator('#sourceRows article').count(),50);await page.locator('#moreSources').click();a.equal(await page.locator('#sourceRows article').count(),77);pass('source inbox limits first render and exposes explicit pagination');
  await page.locator('#inboxIntention').selectOption('project-platform');a.equal(await page.locator('#sourceRows article').count(),37);await page.locator('#inboxQuery').fill('body 15');await page.waitForFunction(()=>document.querySelectorAll('#sourceRows article').length===1);pass('source text and intention filters combine correctly');
  await nav('project','project-platform');await nav('now');a.ok((await page.locator('.launch-resume').innerText()).includes('Platform test project'));await page.reload();await saved();a.ok((await page.locator('.launch-resume').innerText()).includes('Platform test project'));pass('last intention can be resumed after reload without copying its contents into preferences');
  await page.screenshot({path:'test-artifacts/platform-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await nav('install');await page.locator('#platformHealth .device-state').first().waitFor();a.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));a.equal(await page.locator('.mobile-dock').isVisible(),true);await page.screenshot({path:'test-artifacts/platform-phone.png',fullPage:true});pass('390px installation view fits and has accessible thumb-level actions');
  await page.locator('.mobile-dock [data-route="capture"]').click();await page.locator('#captureForm').waitFor();await page.waitForFunction(()=>document.querySelector('#captureForm').getAttribute('aria-busy')==='false');await page.locator('#text').fill('Mobile draft remains');await page.evaluate(()=>flushDraft());await page.locator('.mobile-dock [data-action="commands"]').click();await nav('capture');await page.waitForFunction(()=>document.querySelector('#captureForm').getAttribute('aria-busy')==='false');a.equal(await page.locator('#text').inputValue(),'Mobile draft remains');pass('phone shortcut navigation preserves unfinished capture drafts');
  a.deepEqual(errors,[]);a.ok(serverRequests.every(r=>!r.url.includes('PRIVATE_')));pass('no browser errors and no private text in server URLs');
 }catch(e){await page.screenshot({path:'test-artifacts/platform-failure.png',fullPage:true}).catch(()=>{});throw e;}
 finally{fs.writeFileSync('test-artifacts/platform-results.json',JSON.stringify({passed:results.length,scenarios:results,errors},null,2));await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
