/* Real Chromium, native IndexedDB, Web Crypto and service-worker release tests. */
const {chromium}=require('playwright');
const a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),prefix='/artificial-continuity/',sample=fs.readFileSync(path.join(__dirname,'fixtures/chat-export.json')),results=[],requests=[];
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');requests.push({method:req.method,url:req.url});if(!url.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const f=path.resolve(root,url.pathname.slice(prefix.length)||'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+prefix;
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const ctx=await browser.newContext({viewport:{width:1280,height:920},permissions:['clipboard-read','clipboard-write']});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);
 const pass=n=>{results.push(n);console.log('PASS '+n);};fs.mkdirSync('test-artifacts',{recursive:true});
 const nav=async n=>page.locator('[data-nav="'+n+'"]').click();
 async function intake(){await nav('sources');await page.locator('[data-action="chat-import"]').click();await page.locator('#chatFile').setInputFiles({name:'conversations.json',mimeType:'application/json',buffer:sample});await page.waitForFunction(()=>document.querySelector('#chatStatus').textContent.startsWith('Preview:'));}
 try{
  await page.goto(base);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));a.ok((await page.title()).includes(require('../site/operations-core.js').APP_VERSION));pass('current release starts at a project subpath with native storage');
  await intake();a.equal(await page.locator('.chatChoice:checked').count(),0);a.equal(await page.evaluate(()=>S.sources.length),0);pass('chat export preview never imports or selects records automatically');
  await page.locator('.chatPreview').first().click();a.match(await page.locator('.transcript-preview').innerText(),/Keep the original opening and/);a.doesNotMatch(await page.locator('.transcript-preview').innerText(),/Superseded suggestion/);await page.locator('dialog [data-action="close"]').click();pass('selected current branch excludes an alternative assistant answer');
  await page.locator('#chatBranch-0').selectOption('answer-old');await page.locator('.chatPreview').first().click();a.match(await page.locator('.transcript-preview').innerText(),/Superseded suggestion/);await page.locator('dialog [data-action="close"]').click();await page.locator('#chatBranch-0').selectOption('answer-current');pass('alternate branch is explicitly selectable and previewable');
  await page.locator('.chatChoice').first().check();await page.locator('.chatChoice').nth(1).check();await page.locator('#chatMode').selectOption('separate');await page.locator('#chatSave').click();await page.waitForFunction(()=>S.sources.length===2&&!busy);a.equal(await page.evaluate(()=>S.threads.length),2);a.equal(await page.evaluate(()=>S.notes.length),0);a.equal(await page.evaluate(()=>S.sources[0].chatImport.messages[1].role),'assistant');pass('selected import creates real intentions and sources, not accepted decisions');
  await page.reload();await page.waitForFunction(()=>S?.sources.length===2);pass('imported text and message provenance survive native IndexedDB reload');
  await intake();await page.locator('.chatChoice').first().check();await page.locator('.chatChoice').nth(1).check();await page.locator('#chatMode').selectOption('separate');await page.locator('#chatSave').click();await page.waitForFunction(()=>document.querySelector('#chatStatus').textContent.startsWith('No new sources'));a.equal(await page.evaluate(()=>S.threads.length),2);pass('exact duplicate import creates no extra sources or projects');
  await nav('intentions');await page.locator('[data-action="project"]').first().click();await page.getByRole('heading',{name:'Project sources',exact:true}).waitFor();a.equal(await page.locator('#projectSources article').count(),1);await page.locator('#projectQuery').fill('a word that is not here');a.equal(await page.locator('#projectSources article').count(),0);await page.locator('#projectQuery').fill('');pass('project dossier scopes sources and filters without inventing results');
  await page.screenshot({path:'test-artifacts/v0.13-project-desktop.png',fullPage:true});
  await page.locator('#projectSources [data-action="source"]').click();a.ok((await page.locator('main').innerText()).includes('Speaker labels follow message records'));pass('source view displays branch and omission boundaries');
  await nav('backup');await page.locator('[data-action="sealed-export"]').click();await page.locator('#sealPassword').fill('test-only unique passphrase 2026');await page.locator('#sealRepeat').fill('different test passphrase');await page.locator('#sealForm button.primary').click();a.match(await page.locator('#sealForm [role="alert"]').innerText(),/do not match/);pass('encrypted export rejects mismatched passphrases');
  await page.locator('#sealRepeat').fill('test-only unique passphrase 2026');const exported=page.waitForEvent('download');await page.locator('#sealForm button.primary').click();const dl=await exported;const encrypted=fs.readFileSync(await dl.path());a.doesNotMatch(encrypted.toString(),/original opening|test-only unique/);a.equal(JSON.parse(encrypted).format,'ContinuitySealedBackup/1');pass('Web Crypto backup export downloads ciphertext rather than source text');
  const containsSecret=await page.evaluate(async()=>JSON.stringify(await draftRows()).includes('test-only unique passphrase'));a.equal(containsSecret,false);a.equal(await page.locator('#sealPassword').inputValue(),'');pass('passphrase is cleared and is absent from persistent drafts');
  await nav('capture');await page.locator('#text').fill('Transient capture created after the encrypted backup');await page.locator('#captureConsent').check();await page.locator('#captureForm button.primary').click();await page.waitForFunction(()=>S.captures.length===1&&!busy);await nav('backup');
  await page.locator('#sealedFile').setInputFiles({name:'encrypted.json',mimeType:'application/json',buffer:encrypted});await page.waitForFunction(()=>!document.querySelector('#unlockFile').disabled);const before=await page.evaluate(()=>revision);await page.locator('#unlockPassword').fill('this passphrase is wrong');await page.locator('#unlockFile').click();await page.waitForFunction(()=>document.querySelector('#sealedStatus').textContent.startsWith('Could not decrypt'));a.equal(await page.evaluate(()=>revision),before);a.ok(await page.locator('#restoreSealed').isDisabled());pass('wrong passphrase changes no workspace data');
  await page.locator('#unlockPassword').fill('test-only unique passphrase 2026');await page.locator('#unlockFile').click();await page.waitForFunction(()=>document.querySelector('#sealedStatus').textContent.startsWith('Decrypted preview'));a.equal(await page.evaluate(()=>S.captures.length),1);a.equal(await page.evaluate(()=>revision),before);pass('successful decryption previews without restoring or mutating');
  page.once('dialog',d=>d.dismiss());await page.locator('#restoreSealed').click();a.equal(await page.evaluate(()=>S.captures.length),1);pass('cancelled encrypted restore retains the current workspace');
  page.once('dialog',d=>d.accept());await page.locator('#restoreSealed').click();await page.waitForFunction(()=>S.captures.length===0&&!busy);a.equal(await page.evaluate(async()=>(await store.read('recovery','before-import')).state.captures.length),1);pass('confirmed encrypted restore retains a pre-import recovery copy');
  await nav('backup');const altered=JSON.parse(encrypted);const bytes=Buffer.from(altered.ciphertext,'base64');bytes[0]^=1;altered.ciphertext=bytes.toString('base64');await page.locator('#sealedFile').setInputFiles({name:'changed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(altered))});await page.waitForFunction(()=>!document.querySelector('#unlockFile').disabled);await page.locator('#unlockPassword').fill('test-only unique passphrase 2026');await page.locator('#unlockFile').click();await page.waitForFunction(()=>document.querySelector('#sealedStatus').textContent.startsWith('Could not decrypt'));a.equal(await page.evaluate(()=>S.sources.length),2);pass('tampered ciphertext fails authentication without replacement');
  await page.screenshot({path:'test-artifacts/v0.13-encrypted-backup.png',fullPage:true});
  await intake();await page.locator('#chatFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{not json')});await page.waitForFunction(()=>document.querySelector('#chatStatus').textContent.startsWith('Import rejected'));a.equal(await page.evaluate(()=>S.sources.length),2);pass('invalid conversation export leaves records intact');
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await ctx.setOffline(true);await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Saved'));a.equal(await page.evaluate(()=>typeof PortabilityCore.transcript),'function');a.equal(await page.evaluate(()=>typeof SealedBackup.seal),'function');await intake();a.equal(await page.locator('.chatChoice').count(),2);pass('offline shell contains new importer and encryption modules');await ctx.setOffline(false);
  await page.setViewportSize({width:390,height:844});await nav('intentions');await page.locator('[data-action="project"]').first().click();a.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-artifacts/v0.13-project-mobile.png',fullPage:true});pass('project dossier fits a 390px mobile viewport');
  a.deepEqual(errors,[]);a.equal(requests.filter(r=>r.method!=='GET').length,0);pass('no JavaScript page errors or data-upload requests in tested flows');
 }catch(e){await page.screenshot({path:'test-artifacts/v0.13-failure.png',fullPage:true}).catch(()=>{});throw e;}finally{fs.writeFileSync('test-artifacts/portability-results.json',JSON.stringify({passed:results.length,scenarios:results,errors},null,2));await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
