/* Native WebCrypto + IndexedDB with synthetic fixtures. No user accounts. */
'use strict';
const {chromium}=require('playwright'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const C=require('../site/sync-engine.js'),root=path.resolve(__dirname,'../site'),passed=[],requests=[],errors=[];
const server=http.createServer((req,res)=>{requests.push(req.url);const u=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+(u.pathname.endsWith('/')?u.pathname+'index.html':u.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.js':'application/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'application/json'});res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{let browser;fs.mkdirSync('test-artifacts',{recursive:true});const pass=x=>{passed.push(x);console.log('PASS '+x);};
try{
 const engine=C.createSyncEngine({store:C.createMemoryStore()});await engine.observe({entityId:'synthetic-sync',kind:'task',privacy:'PUBLIC',data:{title:'Synthetic synchronized record',nextAction:'Inspect the readback',summary:'SYNC_PRIVATE_MARKER'},source:{provider:'fixture',externalId:'fixture-mail-1',revision:'1',ref:'https://example.invalid/source',observedAt:'2026-10-08T05:45:00Z'}});const receipt=await engine.receipt();
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const ctx=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true}),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(30000);
 const saved=()=>page.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy&&document.querySelector('#status').textContent.startsWith('Saved'));
 await page.goto('http://127.0.0.1:'+server.address().port+'/#synchronization');await saved();await page.locator('#syncOpen').waitFor();a.ok((await page.locator('#main').innerText()).includes('outside this connector slice'));pass('empty synchronization view has honest provider coverage');
 await page.locator('#syncFile').setInputFiles({name:'synthetic-receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(receipt))});await page.locator('#syncPass').fill('synthetic checkpoint password');await page.locator('#syncOpen').click();await page.locator('#syncSave').waitFor();a.ok((await page.locator('#syncRecord').innerText()).includes('SYNC_PRIVATE_MARKER'));pass('validated receipt opens with inspectable source references');
 await page.locator('#syncSave').click();await page.waitForFunction(()=>document.querySelector('#syncMessage').textContent.includes('Encrypted checkpoint saved'));const cipher=await page.evaluate(()=>store.read('recovery','sync-sealed-checkpoint'));a.ok(!cipher.includes('SYNC_PRIVATE_MARKER'));a.equal(JSON.parse(cipher).format,'ContinuitySealedBackup/1');a.ok(!(await page.evaluate(()=>JSON.stringify(S))).includes('SYNC_PRIVATE_MARKER'));pass('evidence is encrypted in IndexedDB and kept outside unencrypted workspace');
 await page.locator('#syncLock').click();await page.locator('#syncOpen').waitFor();a.ok(!(await page.locator('#main').innerText()).includes('SYNC_PRIVATE_MARKER'));await page.locator('#syncPass').fill('incorrect checkpoint password');await page.locator('#syncOpen').click();await page.waitForFunction(()=>document.querySelector('#syncMessage').textContent.includes('Could not decrypt'));a.equal(await page.evaluate(()=>store.read('recovery','sync-sealed-checkpoint')),cipher);pass('lock clears evidence and wrong passphrase preserves stored ciphertext');
 await page.locator('#syncPass').fill('synthetic checkpoint password');await page.locator('#syncOpen').click();await page.locator('#syncSave').waitFor();const download=page.waitForEvent('download');await page.locator('#syncContext').click();await (await download).saveAs('test-artifacts/sync-context-SYNTHETIC.json');const context=JSON.parse(fs.readFileSync('test-artifacts/sync-context-SYNTHETIC.json','utf8'));a.ok(JSON.stringify(context).includes('synthetic-sync'));pass('a selected private context downloads for model-neutral resumption');
 await page.reload();await saved();await page.locator('#syncPass').fill('synthetic checkpoint password');await page.locator('#syncOpen').click();await page.locator('#syncSave').waitFor();a.ok((await page.locator('#syncRecord').innerText()).includes('SYNC_PRIVATE_MARKER'));pass('encrypted evidence survives browser restart and verified unlock');
 a.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-artifacts/synchronization-mobile.png',fullPage:true});a.ok(requests.every(x=>!x.includes('SYNC_PRIVATE_MARKER')));a.deepEqual(errors,[]);pass('mobile layout and network leakage checks pass');
}finally{fs.writeFileSync('test-artifacts/synchronization-browser-results.json',JSON.stringify({passed:passed.length,scenarios:passed,errors,synthetic:true},null,2));if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
