/* A real pinned previous release, not a mock database. Synthetic user records only. */
const {chromium}=require('playwright');
const a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const nextRoot=path.resolve(__dirname,'../site'),baseline=process.env.CONTINUITY_BASELINE_SITE;
if(!baseline)throw new Error('Set CONTINUITY_BASELINE_SITE to the pinned 0.20.0 site directory.');
let root=path.resolve(baseline);a.ok(fs.readFileSync(path.join(root,'operations-core.js'),'utf8').includes("APP_VERSION='0.20.0'"));
const prefix='/artificial-continuity/',results=[],errors=[];
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const f=path.resolve(root,u.pathname.slice(prefix.length)||'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;fs.mkdirSync('test-artifacts',{recursive:true});
 const pass=s=>{results.push(s);console.log('PASS '+s);};
 try{
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
  const saved=()=>page.waitForFunction(()=>typeof S!=='undefined'&&S&&!busy&&document.querySelector('#status').textContent.startsWith('Saved'));
  await page.goto('http://127.0.0.1:'+server.address().port+prefix);await saved();a.equal(await page.evaluate(()=>O.APP_VERSION),'0.20.0');await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);pass('real 0.20.0 shell installed');
  await page.locator('[data-nav="fast-intake"]').click();const original='Name: Upgrade fixture\nGoal: Preserve exact evidence\nLast: Drafted a paragraph\nNext: Check the example\nQuestions: Which reader?\nState: CONTINUE\nWaiting:\n';await page.locator('#intakeRaw').fill(original);await page.locator('#intakePreview').click();await page.locator('#intakeSave').click();await saved();await page.waitForURL('**/#project/*');const id=await page.evaluate(()=>S.threads[0].id);await page.evaluate(id=>navigate('assistant',id),id);await page.waitForFunction(()=>document.querySelector('#bridgeQuestionForm')?.getAttribute('aria-busy')==='false');
  await page.locator('#bridgeQuestion').fill('Preserve this unsent question across the update.');const before=await page.evaluate(()=>JSON.parse(JSON.stringify(S)));pass('synthetic record, source and unsent draft created in old release');
  root=nextRoot;await page.evaluate(()=>appRegistration.update());await page.waitForFunction(()=>!!appRegistration?.waiting);await page.locator('#applyUpdate').waitFor({state:'visible'});a.equal(await page.evaluate(()=>O.APP_VERSION),'0.20.0');pass('new release is offered without forcing a reload');
  await Promise.all([new Promise((resolve,reject)=>page.once('dialog',d=>d.dismiss().then(resolve,reject))),page.locator('#applyUpdate').click()]);a.equal(await page.evaluate(()=>O.APP_VERSION),'0.20.0');a.deepEqual(await page.evaluate(()=>S),before);pass('cancelling the update retains the old app and records');
  await Promise.all([new Promise((resolve,reject)=>page.once('dialog',d=>d.accept().then(resolve,reject))),page.locator('#applyUpdate').click()]);await page.waitForFunction(()=>typeof O!=='undefined'&&O.APP_VERSION==='0.20.1');await saved();await page.waitForFunction(()=>document.querySelector('#bridgeQuestionForm')?.getAttribute('aria-busy')==='false');
  a.deepEqual(await page.evaluate(()=>S),before);a.equal(await page.locator('#bridgeQuestion').inputValue(),'Preserve this unsent question across the update.');a.equal(await page.evaluate(()=>S.sources[0].text),original);a.equal(await page.evaluate(()=>S.version),'0.11.0');pass('approved update preserves exact state, original source and recovered draft');
  await ctx.setOffline(true);await page.reload();await saved();a.equal(await page.evaluate(()=>O.APP_VERSION),'0.20.1');pass('new shell reloads offline');
  const [help]=await Promise.all([ctx.waitForEvent('page'),page.locator('nav a[href="./help.html"]').click()]);await help.waitForLoadState('load');a.ok((await help.title()).includes('0.20.1'));a.ok((await help.locator('h1').innerText()).includes('easier to resume'));a.equal(await help.locator('link[rel="stylesheet"]').evaluate(e=>!!e.sheet),true);a.ok(await help.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await help.screenshot({path:'test-artifacts/upgrade-guide-offline-mobile.png',fullPage:true});pass('guide and styles are available offline with no mobile overflow');
  a.deepEqual(errors,[]);pass('no browser script errors during upgrade');
 }finally{fs.writeFileSync('test-artifacts/update-results.json',JSON.stringify({passed:results.length,scenarios:results,errors,baselineCommit:'ea41a077e753f90fb78de8e2e406b5f5af05f052',physicalDevice:false},null,2));if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
