/* Real Chromium tests on a subpath, with native IndexedDB and offline service worker. */
const {chromium}=require('playwright');
const a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../site'),prefix='/artificial-continuity/',results=[],requests=[];
const server=http.createServer((req,res)=>{requests.push({method:req.method,url:req.url});const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}const f=path.resolve(root,u.pathname.slice(prefix.length)||'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{const b=fs.readFileSync(f);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(f)]||'text/plain','Cache-Control':'no-store'});res.end(b);}catch{res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+prefix;
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const ctx=await browser.newContext({viewport:{width:1280,height:950}}),page=await ctx.newPage(),errors=[];
 page.setDefaultTimeout(18000);page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('test-artifacts',{recursive:true});
 const pass=n=>{results.push(n);console.log('PASS '+n);};
 const saved=()=>page.waitForFunction(()=>!busy&&document.querySelector('#status').textContent.startsWith('Saved'));
 const go=async r=>{await page.goto(base+'#'+r);await saved();if(r==='review'){await page.locator('#reviewBatch[aria-busy="false"]').waitFor();await page.locator('#reviewText').fill('');await page.locator('#filterReview').click();}};
 try{
  await go('review');await page.getByRole('heading',{name:'No pending checkpoints in this view.'}).waitFor();a.ok((await page.title()).includes(require('../site/operations-core.js').APP_VERSION));pass('review deep link opens correctly with native storage');
  await page.locator('[data-nav="intentions"]').click();await page.locator('main [data-action="new-thread"]').first().click();await page.locator('#title').fill('Write the essay');await page.locator('#objective').fill('Finish the source-backed essay.');await page.locator('#last').fill('Outline ready');await page.locator('#next').fill('Draft opening');await page.locator('#threadForm button.primary').click();await saved();await page.waitForSelector('#dialog',{state:'hidden'});const tid=await page.evaluate(()=>S.threads[0].id);
  await page.evaluate(async id=>{await mutate('TEST_PENDING_FIXTURE','Prepare pending imported checkpoints for review tests.',s=>{const src=W.makeSource(s,{title:'Imported evidence',text:'User: Preserve my wording.\nAssistant: Rewrite everything.\nUser: What is still uncertain?\n<img src=x onerror="window.injected=true">',threadId:id,speaker:'mixed'},'review-src',now());s.sources.push(src);for(let i=0;i<3;i++){const n=W.checkpoint(s,{threadId:id,sourceId:src.id,kind:i===2?'question':'constraint',statement:'Imported proposal '+i,start:i+1,end:i+1,reviewed:true},'pending-'+i,now());n.reviewState='pending';s.notes.push(n);}});},tid);
  const original=await page.evaluate(()=>S.sources.find(x=>x.id==='review-src').text);
  await page.locator('[data-nav="review"]').click();await page.locator('#reviewBatch[aria-busy="false"]').waitFor();a.equal(await page.locator('[id^="reviewPick"]:checked').count(),0);a.equal(await page.locator('#saveReview').isDisabled(),true);pass('pending evidence is displayed without preselected acceptance');
  await page.locator('#reviewStatement0').fill('Preserve my original wording.');await page.locator('#reviewPick0').check();await page.waitForFunction(()=>document.querySelector('main .draft-status').textContent.includes('Draft saved'));await page.reload();await saved();await page.locator('#reviewBatch[aria-busy="false"]').waitFor();a.equal(await page.locator('#reviewStatement0').inputValue(),'Preserve my original wording.');a.equal(await page.locator('#reviewPick0').isChecked(),false);pass('interpretation drafts survive reload but acceptance never does');
  await page.locator('#reviewPick0').check();await page.locator('#reviewPick2').check();await page.locator('#saveReview').click();await saved();await page.waitForFunction(()=>S.notes.filter(x=>x.reviewState==='pending').length===1);a.equal(await page.evaluate(()=>S.sources.find(x=>x.id==='review-src').text),original);a.equal(await page.evaluate(()=>S.notes.find(x=>x.id==='pending-0').reviewedFrom.statement),'Imported proposal 0');a.equal(await page.evaluate(()=>S.notes.find(x=>x.id==='pending-1').reviewState),'pending');pass('batch confirmation applies only selected items and preserves both original source and prior interpretation');
  await go('pack/'+tid);await page.locator('#packText').waitFor();const pack=await page.locator('#packText').inputValue();a.ok(pack.includes('Preserve my original wording.'));a.ok(!pack.includes('Imported proposal 1'));pass('resume pack includes newly reviewed evidence and excludes unselected proposals');
  await go('review');await page.locator('#reviewBatch[aria-busy="false"]').waitFor();await page.locator('#reviewText').fill('unfindablequokka');await page.locator('#filterReview').click();await page.getByRole('heading',{name:'No pending checkpoints in this view.'}).waitFor();a.equal(await page.evaluate(()=>S.notes.filter(x=>x.reviewState==='pending').length),1);pass('review filter hides records without changing their pending state');
  await go('work/'+tid);await page.locator('#progressForm[aria-busy="false"]').waitFor();await page.locator('#workProgress').fill('  Wrote an opening.\nKeep these spaces.  ');await page.locator('#workNext').fill('Review the final paragraph');await page.waitForFunction(()=>document.querySelector('main .draft-status').textContent.includes('Draft saved'));await page.reload();await saved();await page.locator('#progressForm[aria-busy="false"]').waitFor();a.equal(await page.locator('#workProgress').inputValue(),'  Wrote an opening.\nKeep these spaces.  ');pass('short progress form recovers exact unfinished draft after reload');
  const count=await page.evaluate(()=>S.sources.length);await page.locator('#progressForm button.primary').click();await page.locator('#commitProgress').waitFor();a.equal(await page.evaluate(()=>S.sources.length),count);a.equal(await page.locator('[data-progress-field]:checked').count(),0);await page.locator('[data-progress-field="last"]').check();await page.locator('[data-progress-field="next"]').check();await page.locator('#commitProgress').click();await saved();await page.waitForURL('**/#project/*');a.equal(await page.evaluate(()=>S.threads[0].next),'Review the final paragraph');a.equal(await page.evaluate(()=>S.threads[0].state),'CONTINUE');a.ok((await page.evaluate(()=>S.sources.at(-1).text)).includes('  Wrote an opening.\nKeep these spaces.  '));pass('preview commits exact work note and only explicitly selected intention fields');
  await go('work/'+tid);await page.locator('#progressForm[aria-busy="false"]').waitFor();await page.locator('#workProgress').fill('A new note without changing my current position.');await page.locator('#progressForm button.primary').click();await page.locator('#commitProgress').click();await saved();await page.waitForURL('**/#project/*');a.equal(await page.evaluate(()=>S.threads[0].last),'Wrote an opening.\nKeep these spaces.');pass('saving a source-only progress note does not overwrite the last position');
  await go('work/'+tid);await page.locator('#progressForm[aria-busy="false"]').waitFor();await page.locator('#workProgress').fill('<img src=x onerror="window.injected=true">');await page.locator('#progressForm button.primary').click();await page.locator('#commitProgress').waitFor();a.equal(await page.locator('#progressPreview img').count(),0);await page.locator('#workProgress').fill('Revised before committing.');a.equal(await page.locator('#progressPreview').isVisible(),false);pass('markup is inert and editing invalidates the old progress preview');
  await page.locator('#progressForm details summary').click();await page.locator('#workState').selectOption('WAITING');await page.locator('#workWaiting').fill('Another person needs to review it');await page.locator('#progressForm button.primary').click();await page.locator('[data-progress-field="state"]').check();await page.locator('#commitProgress').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('needs a reason'));a.equal(await page.evaluate(()=>S.threads[0].state),'CONTINUE');await page.locator('[data-progress-field="waiting"]').check();await page.locator('#commitProgress').click();await saved();await page.waitForURL('**/#project/*');a.equal(await page.evaluate(()=>S.threads[0].state),'WAITING');pass('waiting-state change fails without a reason and succeeds only with the selected reason');
  await go('review');await page.locator('#reviewBatch[aria-busy="false"]').waitFor();await page.locator('#reviewPick0').check();const peer=await ctx.newPage();await peer.goto(base);await peer.waitForFunction(()=>!!S&&!busy);await peer.evaluate(async()=>{await mutate('TEST_PEER_EDIT','Concurrent saved change',s=>s.notes.find(n=>n.reviewState==='pending').statement='Changed on the other tab.');});await page.locator('#saveReview').click();await page.waitForFunction(()=>document.querySelector('#reload').hidden===false);a.equal(await page.evaluate(()=>S.notes.find(n=>n.id==='pending-1').reviewState),'pending');await peer.close();pass('native revision conflict prevents a stale review tab from overwriting newer work');
  await page.locator('#reload').click();await saved();await page.locator('#reviewBatch[aria-busy="false"]').waitFor();a.equal(await page.locator('#reviewPick0').isChecked(),false);
  await page.setViewportSize({width:390,height:844});a.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'test-artifacts/v017-review-phone.png',fullPage:true});await go('work/'+tid);await page.locator('#progressForm[aria-busy="false"]').waitFor();a.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'test-artifacts/v017-progress-phone.png',fullPage:true});pass('review and progress forms fit a 390px phone viewport');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await ctx.setOffline(true);await page.reload();await saved();await page.locator('#progressForm[aria-busy="false"]').waitFor();await page.locator('#workProgress').fill('A real offline progress note.');await page.locator('#progressForm button.primary').click();await page.locator('#commitProgress').click();await saved();await page.waitForURL('**/#project/*');await page.reload();await saved();a.ok(await page.evaluate(()=>S.sources.some(x=>x.text.includes('A real offline progress note.'))));await ctx.setOffline(false);pass('cached workflow reloads and stores progress offline with native IndexedDB');
  await page.setViewportSize({width:1366,height:950});await go('review');await page.screenshot({path:'test-artifacts/v017-review-desktop.png',fullPage:true});a.deepEqual(errors,[]);a.ok(requests.every(r=>r.method==='GET'));a.ok(!requests.some(r=>r.url.includes('Wrote')||r.url.includes('paragraph')));pass('no uncaught script errors and no network writes of user content');
  fs.writeFileSync('test-artifacts/workflow-results.json',JSON.stringify({passed:results.length,scenarios:results},null,2));
 }catch(e){console.error(e);await page.screenshot({path:'test-artifacts/v017-failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('test-artifacts/workflow-failure.txt',e.stack+'\n'+errors.join('\n'));throw e;}
 finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
